=== akarnokd/open-ig/trunk/open-ig-0.95/data/generic/schemas/bridge.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="bridge" type="bridge">
		<xs:annotation>
			<xs:documentation>Defines the appearance and messages of the bridge screen.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="bridge">
		<xs:annotation><xs:documentation>The bridge definition.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="graphics" type="graphics">
				<xs:annotation><xs:documentation>The definition of bridge for various levels.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="messages" type="messages">
				<xs:annotation><xs:documentation>The definition of send and receive messages.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="graphics">
		<xs:annotation><xs:documentation>The graphical definition of the bridge at various levels.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="level" type="level" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The graphical definition of a single level bridge.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="level">
		<xs:annotation><xs:documentation>The graphical definition of a single level bridge.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="message-panel" type="message-panel">
				<xs:annotation><xs:documentation>The message panel definition where the incoming and outgoung messages are listed.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="comm-panel" type="comm-panel">
				<xs:annotation><xs:documentation>The communication panel where the messages are played.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The level identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="image" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The resource reference of the bridge's background image.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="ship-id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>Reference to the ship walking in the walks.xml .</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="message-panel">
		<xs:annotation><xs:documentation>The graphical definition of the message panel.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="appear" type="video-audio">
				<xs:annotation><xs:documentation>The video animation to play when the message panel appears.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="open" type="video-audio">
				<xs:annotation><xs:documentation>The video animation to play when the message panel is opened.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="close" type="video-audio">
				<xs:annotation><xs:documentation>The video animation to play when the message panel is closed.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="buttons" type="message-buttons">
				<xs:annotation><xs:documentation>The button images.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="video-audio">
		<xs:annotation><xs:documentation>The references to the audio and video resources.</xs:documentation></xs:annotation>
		<xs:attribute name="video" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The resource reference to the video.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="audio" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The resource reference to the audio.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="message-buttons">
		<xs:annotation><xs:documentation>The definition of button images on the message panel.</xs:documentation></xs:annotation>
		<xs:attribute name="up" type="xs:string" use="required">
			<xs:annotation><xs:documentation>Resource referencing the up button image.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="down" type="xs:string" use="required">
			<xs:annotation><xs:documentation>Resource referencing the down button image.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="send" type="xs:string" use="required">
			<xs:annotation><xs:documentation>Resource referencing the send button image.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="receive" type="xs:string" use="required">
			<xs:annotation><xs:documentation>Resource referencing the receive button image.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="comm-panel">
		<xs:annotation><xs:documentation>The graphical definition of the message panel.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="open" type="video-audio">
				<xs:annotation><xs:documentation>The video animation to play when the communication panel is opened.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="close" type="video-audio">
				<xs:annotation><xs:documentation>The video animation to play when the communication panel is closed.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="messages">
		<xs:annotation><xs:documentation>The definition of incoming and outgoing messages.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="send" type="message-list">
				<xs:annotation><xs:documentation>The messages to send out.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="receive" type="message-list">
				<xs:annotation><xs:documentation>The messages to receive.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="message-list">
		<xs:annotation><xs:documentation>The list of messages.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="message" type="message" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The message definition.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="message">
		<xs:annotation><xs:documentation>The message definition.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The unique identifier of the message.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="media" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The resource reference to the media (audio, video and subtitle) to play.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="title" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label to display as the message title.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label to display as the secondary message title.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig-0.95/data/generic/campaign/main/bridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<bridge xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/bridge.xsd">
	<graphics>
		<level id="1" image="flagship/bridge_level_1" ship-id="1">
			<message-panel>
				<appear video="bridge/messages_appear_level_1" audio=""/>
				<open video="bridge/messages_open_level_1" audio="ui/messages_deploy"/>
				<close video="bridge/messages_close_level_1" audio="ui/messages_deploy"/>
				<buttons up="flagship/button_upwards_level_1" send="flagship/button_send_level_1" receive="flagship/button_receive_level_1" down="flagship/button_downwards_level_1"/>
			</message-panel>
			<comm-panel>
				<open video="bridge/projector_extend_level_1" audio="ui/comm_deploy"/>
				<close video="bridge/projector_retract_level_1" audio="ui/comm_deploy"/>
			</comm-panel>
		</level>
		<level id="2" image="flagship/bridge_level_2" ship-id="2">
			<message-panel>
				<appear video="bridge/messages_appear_level_2" audio=""/>
				<open video="bridge/messages_open_level_2" audio="ui/messages_deploy"/>
				<close video="bridge/messages_close_level_2" audio="ui/messages_deploy"/>
				<buttons up="flagship/button_upwards_level_2" send="flagship/button_send_level_2" receive="flagship/button_receive_level_2" down="flagship/button_downwards_level_2"/>
			</message-panel>
			<comm-panel>
				<open video="bridge/projector_extend_level_2" audio="ui/comm_deploy"/>
				<close video="bridge/projector_retract_level_2" audio="ui/comm_deploy"/>
			</comm-panel>
		</level>
		<level id="3" image="flagship/bridge_level_3" ship-id="3">
			<message-panel>
				<appear video="bridge/messages_appear_level_3" audio=""/>
				<open video="bridge/messages_open_level_3" audio="ui/messages_deploy"/>
				<close video="bridge/messages_close_level_3" audio="ui/messages_deploy"/>
				<buttons up="flagship/button_upwards_level_3" send="flagship/button_send_level_3" receive="flagship/button_receive_level_3" down="flagship/button_downwards_level_3"/>
			</message-panel>
			<comm-panel>
				<open video="bridge/projector_extend_level_3" audio="ui/comm_deploy"/>
				<close video="bridge/projector_retract_level_3" audio="ui/comm_deploy"/>
			</comm-panel>
		</level>
		<level id="4" image="flagship/bridge_level_3" ship-id="4">
			<message-panel>
				<appear video="bridge/messages_appear_level_3" audio=""/>
				<open video="bridge/messages_open_level_3" audio="ui/messages_deploy"/>
				<close video="bridge/messages_close_level_3" audio="ui/messages_deploy"/>
				<buttons up="flagship/button_upwards_level_3" send="flagship/button_send_level_3" receive="flagship/button_receive_level_3" down="flagship/button_downwards_level_3"/>
			</message-panel>
			<comm-panel>
				<open video="bridge/projector_extend_level_3" audio="ui/comm_deploy"/>
				<close video="bridge/projector_retract_level_3" audio="ui/comm_deploy"/>
			</comm-panel>
		</level>
		<level id="5" image="flagship/bridge_level_3" ship-id="4">
			<message-panel>
				<appear video="bridge/messages_appear_level_3" audio=""/>
				<open video="bridge/messages_open_level_3" audio="ui/messages_deploy"/>
				<close video="bridge/messages_close_level_3" audio="ui/messages_deploy"/>
				<buttons up="flagship/button_upwards_level_3" send="flagship/button_send_level_3" receive="flagship/button_receive_level_3" down="flagship/button_downwards_level_3"/>
			</message-panel>
			<comm-panel>
				<open video="bridge/projector_extend_level_3" audio="ui/comm_deploy"/>
				<close video="bridge/projector_retract_level_3" audio="ui/comm_deploy"/>
			</comm-panel>
		</level>
	</graphics>
	<messages>
		<send>
			<message id="Achilles-Check" media="messages/achilles_check" title="messages.Achilles" description="messages.check"/>
			<message id="Achilles-Come-Quickly" media="messages/achilles_come_quickly" title="messages.Achilles" description="messages.check"/>
			<message id="Achilles-Not-Under-Attack" media="messages/achilles_not_under_attack" title="messages.Achilles" description="messages.check"/>
			<message id="Centronom-Check" media="messages/centronom_check" title="messages.Centronom" description="messages.check"/>
			<message id="Centronom-Come-Quickly" media="messages/centronom_come_quickly" title="messages.Centronom" description="messages.check"/>
			<message id="Centronom-Not-Under-Attack" media="messages/centronom_not_under_attack" title="messages.Centronom" description="messages.check"/>
			<message id="Naxos-Check" media="messages/naxos_no_problem" title="messages.Naxos" description="messages.check"/>
			<message id="Naxos-Come-Quickly" media="messages/naxos_come_quickly" title="messages.Naxos" description="messages.check"/>
			<message id="Naxos-Not-Under-Attack" media="messages/naxos_not_under_attack" title="messages.Naxos" description="messages.check"/>
			<message id="New Caroline-Check" media="messages/new_caroline_check" title="messages.New Caroline" description="messages.check"/>
			<message id="New Caroline-Come-Quickly" media="messages/new_caroline_come_quickly" title="messages.New Caroline" description="messages.check"/>
			<message id="New Caroline-Not-Under-Attack" media="messages/new_caroline_not_under_attack" title="messages.New Caroline" description="messages.check"/>
			<message id="San Sterling-Check" media="messages/san_sterling_check" title="messages.San Sterling" description="messages.check"/>
			<message id="San Sterling-Come-Quickly" media="messages/san_sterling_come_quickly" title="messages.San Sterling" description="messages.check"/>
			<message id="San Sterling-Not-Under-Attack" media="messages/san_sterling_not_under_attack" title="messages.San Sterling" description="messages.check"/>
			<message id="Zeuson-Check" media="messages/zeuson_check" title="messages.Zeuson" description="messages.check"/>
			<message id="Zeuson-Come-Quickly" media="messages/zeuson_come_quickly" title="messages.Zeuson" description="messages.check"/>
			<message id="Zeuson-Not-Under-Attack" media="messages/zeuson_not_under_attack" title="messages.Zeuson" description="messages.check"/>
			<message id="Douglas-Thorin-Reinforcements" media="messages/douglas_escort_thorin_reinforcements" title="messages.reinforcements" description="messages.thorin"/>
			<message id="Douglas-Report-Spy" media="messages/douglas_report_spy" title="messages.douglas" description="messages.spy"/>
			<message id="Douglas-Report-Viruses" media="messages/douglas_report_viruses" title="messages.douglas" description="messages.viruses"/>
			<message id="Douglas-Reinforcements-Approved" media="messages/douglas_reinforcements_approved" title="messages.douglas" description="messages.reinforcements"/>
			<message id="Douglas-Reinforcements-Denied" media="messages/douglas_reinforcements_denied" title="messages.douglas" description="messages.reinforcements"/>
			<message id="Douglas-Reinforcements-Denied-2" media="messages/douglas_reinforcements_again_denied" title="messages.douglas" description="messages.reinforcements"/>
			<message id="Android" media="messages/android" title="messages.android" description="messages.android_truth"/>
			<message id="Douglas-Virus-Carriers-Destroyed" media="messages/douglas_virus_carriers_destroyed" title="messages.douglas" description="messages.virus_carriers_destroyed"/>
		</send>
		<receive>
			<message id="Achilles-Is-Under-Attack" media="messages/achilles_is_under_attack" title="messages.Achilles" description="messages.is_attack"/>
			<message id="Achilles-Under-Attack" media="messages/achilles_under_attack" title="messages.Achilles" description="messages.attack"/>
			<message id="Achilles-Virus" media="messages/achilles_virus_infection" title="messages.Achilles" description="messages.virus"/>
			<message id="Centronom-Is-Under-Attack" media="messages/centronom_is_under_attack" title="messages.Centronom" description="messages.is_attack"/>
			<message id="Centronom-Virus" media="messages/centronom_virus_infection" title="messages.Centronom" description="messages.virus"/>
			<message id="Naxos-Is-Under-Attack" media="messages/naxos_is_under_attack" title="messages.Naxos" description="messages.is_attack"/>
			<message id="Naxos-Under-Attack" media="messages/naxos_under_attack" title="messages.Naxos" description="messages.attack"/>
			<message id="Naxos-Unknown-Ships" media="messages/naxos_unknown_ships_nearby" title="messages.Naxos" description="messages.unknown"/>
			<message id="Naxos-Virus" media="messages/naxos_virus_infection" title="messages.Naxos" description="messages.virus"/>
			<message id="New Caroline-Is-Under-Attack" media="messages/new_caroline_is_under_attack" title="messages.New Caroline" description="messages.is_attack"/>
			<message id="New Caroline-Under-Attack" media="messages/new_caroline_under_attack" title="messages.New Caroline" description="messages.attack"/>
			<message id="New Caroline-Virus" media="messages/new_caroline_virus_infection" title="messages.New Caroline" description="messages.virus"/>
			<message id="New Caroline-Garthog-Virus" media="messages/new_caroline_virus" title="messages.New Caroline" description="messages.virus"/>
			<message id="New Caroline-Garthog-Virus-Again" media="messages/new_caroline_virus_again" title="messages.New Caroline" description="messages.virus_again"/>
			<message id="New Caroline-Garthog-Virus-Again-Deaths" media="messages/new_caroline_virus_again_deaths" title="messages.New Caroline" description="messages.virus_again_deaths"/>
			<message id="New Caroline-Garthog-Virus-Breached" media="messages/new_caroline_virus_quarantine_breached" title="messages.New Caroline" description="messages.virus_breached"/>
			<message id="New Caroline-Garthog-Virus-Resolved" media="messages/new_caroline_virus_resolved" title="messages.New Caroline" description="messages.virus_resolved"/>
