=== akarnokd/open-ig/trunk/open-ig-0.95/data/generic/schemas/chat.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="chats" type="chats">
		<xs:annotation><xs:documentation>Description of various chat options.</xs:documentation></xs:annotation>
	</xs:element>
	<xs:complexType name="chats">
		<xs:annotation><xs:documentation>List of chat alternatives.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="chat" type="chat" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>A single chat option.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="chat">
		<xs:annotation><xs:documentation>A single chat option. The chat always starts with node id="0".</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="node" type="node" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>A chat node.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The unique identifier of the chat option.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="node">
		<xs:annotation><xs:documentation>A chat option.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="transition" type="transition" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The available subsequent nodes for this current node.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The locally-unique chat node id. Special nodes: "0" is the start node, "-1" is the retreat node in case of hitpoints get down to half.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="owner" type="owner" use="required">
			<xs:annotation><xs:documentation>The message will be displayed for this player.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="option" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The string label to display as a selectable option. Used if the regular message would be too long.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="message" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The message label to print into the chat box.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="action" type="action" use="optional">
			<xs:annotation><xs:documentation>The action to take if this option is chosen.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="owner">
		<xs:annotation><xs:documentation>The enumeration for the message owner.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="player">
				<xs:annotation><xs:documentation>Option presented to the current player.</xs:documentation></xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="enemy">
				<xs:annotation><xs:documentation>Option chosen by the enemy of the player.</xs:documentation></xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="transition">
		<xs:annotation><xs:documentation>Transition from one chat node to another.</xs:documentation></xs:annotation>
		<xs:attribute name="to" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The next node's identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="action">
		<xs:annotation><xs:documentation>The available actions for a chat node.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="retreat">
				<xs:annotation><xs:documentation>The actor should retreat.</xs:documentation></xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/chat.xml
<?xml version="1.0" encoding="UTF-8"?>
<chats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/chat.xsd">
	<!-- messages when attack merchant and not related to any mission. -->
	<chat id="chat.nomission.attack.merchant1">
		<node owner="enemy" message="chat.global.dont_shoot" id="-1" action="retreat"/>
		<node id="0" owner="player" message="chat.global.identify_yourself">
			<transition id="t1" to="1"/>
		</node>
		<node id="1" owner="enemy" message="This is ship MOB451 on a trading route.">
			<transition id="t2" to="2"/>
			<transition id="t3" to="3"/>
		</node>
		<node id="2" owner="player" message="chat.global.proceed_your_destination">
			<transition id="t4" to="4"/>
		</node>
		<node id="3" owner="player" message="I'm sure you're pirates. Prepare to die!">
			<transition id="t5" to="5"/>
		</node>
		<node id="4" owner="enemy" message="chat.global.thank_you" action='retreat'/>
		<node id="5" owner="enemy" message="Don't shoot! We are innocent merchants!">
			<transition id="t6" to="6"/>
			<transition id="t7" to="7"/>
		</node>
		<node id="6" owner="player" option="Die!" message="I'm sure you are pirates. Prepare to die!">
			<transition id="t8" to="8"/>
		</node>
		<node id="7" owner="player" option="All right. Proceed to your destination!" message="chat.global.proceed_your_destination">
			<transition id="t4" to="4"/>
		</node>
		<node id="8" owner="enemy" message="Don't shoot! Don't shoot! We'll turn around!" action="retreat"/>
	</chat>
	<chat id="chat.nomission.attack.merchant2">
		<node id="0" owner="player" message="chat.global.identify_yourself">
			<transition id="t1" to="1"/>
		</node>
		<node id="1" owner="enemy" message=">This is ship MX43 on a trading route.">
			<transition id="t2" to="2"/>
			<transition id="t3" to="3"/>
		</node>
		<node id="2" owner="player" message="Please carry on!">
			<transition id="t4" to="4"/>
		</node>
		<node id="3" owner="player" message="Yeah? Whose leg are you trying to pull?">
			<transition id="t5" to="5"/>
		</node>
		<node id="4" owner="enemy" message="chat.global.thank_you" action="retreat"/>
		<node id="5" owner="enemy" message="What?! We are just harmless traders!">
			<transition id="t6" to="6"/>
			<transition id="t7" to="7"/>
		</node>
		<node id="6" owner="player" message="Unfortunately, I don't believe you. Die!">
			<transition id="t8" to="8"/>
		</node>
		<node id="7" owner="player" message="OK. I'll let you pass.">
			<transition id="t4" to="4"/>
		</node>
		<node id="8" owner="enemy" message="Hey! Don't fire! We're going, you trigger happy maniac!" action="retreat"/>
	</chat>
	<chat id="chat.nomission.attack.merchant3">
		<node id="0" owner="player" message="Ship, please state name and destination!">
			<transition id="t1" to="1"/>
		</node>
		<node id="1" owner="enemy" message="This is ECHO, following a trading course.">
			<transition id="t2" to="2"/>
			<transition id="t3" to="3"/>
		</node>
		<node id="2" owner="player" message="Thank's, ECHO. Continue on present course.">
			<transition id="t4" to="4"/>
		</node>
		<node id="3" owner="player" option="Hey! I could use a bit of target practice!" message="Are you interested in explosions?">
			<transition id="t5" to="5"/>
		</node>
		<node id="4" owner="enemy" message="Thank you very much!" action="retreat"/>
		<node id="5" owner="enemy" message="You must be crazy!">
			<transition id="t6" to="6"/>
			<transition id="t7" to="7"/>
		</node>
		<node id="6" owner="player" message="Not intersted? That's a real shame...">
			<transition id="t8" to="8"/>
		</node>
		<node id="7" owner="player" message="Go on, you've caught me on a good day.">
			<transition id="t4" to="4"/>
		</node>
		<node id="8" owner="enemy" message="I've got a bad feeling about this... I'm outta here!" action="retreat"/>
	</chat>
	<chat id="chat.nomission.attack.merchant4">
		<node id="0" owner="player" message="chat.global.identify_yourself">
			<transition id="t1" to="1"/>
		</node>
		<node id="1" owner="enemy" message="This is the trading ship Bravox.">
			<transition id="t2" to="2"/>
			<transition id="t3" to="3"/>
		</node>
		<node id="2" owner="player" message="Bravox, proceed to your destination!">
			<transition id="t4" to="4"/>
		</node>
		<node id="3" owner="player" option="How much will you pay?" message="How much will you pay, for not being turned into space debris?">
			<transition id="t5" to="5"/>
		</node>
		<node id="4" owner="enemy" message="chat.global.thank_you" action="retreat"/>
		<node id="5" owner="enemy" message="Hey! I'm sure your commander will be unhappy to hear of this behaviour!">
			<transition id="t6" to="6"/>
			<transition id="t7" to="7"/>
		</node>
		<node id="6" owner="player" message="No cash? Prepare to be destroyed!">
			<transition id="t8" to="8"/>
		</node>
		<node id="7" owner="player" option="Only joking, Bravox, you may proceed!" message="Bravox, proceed to your destination!">
			<transition id="t4" to="4"/>
		</node>
		<node id="8" owner="enemy" message="This is outrageous! I think we had better leave..." action="retreat"/>
	</chat>
	<chat id="chat.nomission.attack.merchant5">
		<node id="0" owner="player" message="Ship, please identify.">
			<transition id="t1" to="1"/>
		</node>
		<node id="1" owner="enemy" message="This is the trade ship Max4.">
			<transition id="t2" to="2"/>
			<transition id="t3" to="3"/>
		</node>
		<node id="2" owner="player" message="Continue on present course, Max4!">
			<transition id="t4" to="4"/>
		</node>
		<node id="3" owner="player" option="Trade ship? You look like Bandits to me!" message="Trade ship? You look like Bandits to me! If you pay me, I might let you go...">
			<transition id="t5" to="5"/>
		</node>
		<node id="4" owner="enemy" message="Good! I was just about to call my Lawyer." action="retreat"/>
		<node id="5" owner="enemy" message="I spent all my money on this ship! But if you let me go I will pay you later.">
			<transition id="t6" to="6"/>
			<transition id="t7" to="7"/>
		</node>
		<node id="6" owner="player" message="I don't believe you, pay or pray!">
			<transition id="t8" to="8"/>
		</node>
		<node id="7" owner="player" message="Get lost, before I change my mind!">
			<transition id="t4" to="4"/>
		</node>
		<node id="8" owner="enemy" message="Please don't shoot me! I didn't do anything! Your lawyer will hear about this!">
			<transition id="t9" to="9"/>
			<transition id="t10" to="10"/>
		</node>
		<node id="9" owner="player" message="You leave me no choice! You must die!">
			<transition id="t11" to="11"/>
		</node>
		<node id="10" owner="player" message="Miserable wretch! Get out of my sight!">
			<transition id="t12" to="12"/>
		</node>
		<node id="11" owner="enemy" message="I'm going! I can see that you are an unreasonable man..." action="retreat"/>
		<node id="12" owner="enemy" message="Ok, but don't expect me to forget this!" action="retreat"/>
	</chat>
	<chat id="chat.nomission.attack.merchant6">
		<node id="0" owner="player" message="chat.global.identify_yourself">
			<transition id="t1" to="1"/>
		</node>
		<node id="1" owner="enemy" message="This is spaceship Horse on a trading route.">
			<transition id="t2" to="2"/>
			<transition id="t3" to="3"/>
		</node>
		<node id="2" owner="player" message="Continue to your destination!">
			<transition id="t4" to="4"/>
		</node>
		<node id="3" owner="player" option="Why are you flying around?" message="Why are you flying around? It makes me mad!">
			<transition id="t5" to="5"/>
		</node>
		<node id="4" owner="enemy" message="Cheers, buddy!" action="retreat"/>
		<node id="5" owner="enemy" message="Sorry bud. Just a bit nervous...">
			<transition id="t6" to="6"/>
			<transition id="t7" to="7"/>
		</node>
		<node id="6" owner="player" message="Die!">
			<transition id="t8" to="8"/>
		</node>
		<node id="7" owner="player" option="All right. I'll let you go." message="Continue to your destination!">
			<transition id="t4" to="4"/>
		</node>
		<node id="8" owner="enemy" message="Don't shoot! Don't shoot! I'll leave!" action="retreat"/>
	</chat>
	<chat id="chat.nomission.attack.merchant7">
		<node id="0" owner="player" message="chat.global.identify_yourself">
			<transition id="t1" to="1"/>
		</node>
		<node id="1" owner="enemy" message="This is ship MX1O9 on a trading route.">
			<transition id="t2" to="2"/>
			<transition id="t3" to="3"/>
		</node>
		<node id="2" owner="player" message="chat.global.proceed_your_destination">
			<transition id="t4" to="4"/>
		</node>
		<node id="3" owner="player" message="So who is a better target, me or you?">
			<transition id="t5" to="5"/>
		</node>
		<node id="4" owner="enemy" message="chat.global.thank_you" action="retreat"/>
		<node id="5" owner="enemy" message="This is an unarmed merchant ship. Let us pass, or we'll report this incident!">
			<transition id="t6" to="6"/>
			<transition id="t7" to="7"/>
		</node>
		<node id="6" owner="player" option="So you want to get away?" message="So you want to get away without fighting? What are you, chicken or McFly?">
			<transition id="t8" to="8"/>
		</node>
		<node id="7" owner="player" option="All right. I'll let you go." message="chat.global.proceed_your_destination">
			<transition id="t4" to="4"/>
		</node>
		<node id="8" owner="enemy" message="As I said, this is a merchant ship. You have 5 seconds to let us on our way, or I will complain to your headquarters.">
			<transition id="t9" to="9"/>
			<transition id="t10" to="10"/>
		</node>
		<node id="9" owner="player" message="So, chicken, die!">
			<transition id="t11" to="11"/>
		</node>
		<node id="10" owner="player" option="All right, I'll let you go." message="chat.global.proceed_your_destination">
			<transition id="t4" to="4"/>
		</node>
