=== akarnokd/open-ig/trunk/open-ig-0.95.131/data/generic/schemas/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="test">
		<xs:annotation>
			<xs:documentation>The questionare.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="question" type="question" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation><xs:documentation>A question definition.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="question">
		<xs:annotation><xs:documentation>A question definition.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="answer" type="answer" minOccurs="2" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The answer definition.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The unique identifier of the question.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label of the question.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="answer">
		<xs:annotation><xs:documentation>The answer definition.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The answer identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The answer label.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="points" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The answer's point value.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/test.xsd">
	<question id="q1" label="test.q1">
		<answer id="a1" label="test.q1.a1" points="0"/>
		<answer id="a2" label="test.q1.a2" points="10"/>
		<answer id="a3" label="test.q1.a3" points="20"/>
	</question>
	<question id="q2" label="test.q2">
		<answer id="a1" label="test.q2.a1" points="20"/>
		<answer id="a2" label="test.q2.a2" points="10"/>
		<answer id="a3" label="test.q2.a3" points="0"/>
	</question>
	<question id="q3" label="test.q3">
		<answer id="a1" label="test.q3.a1" points="20"/>
		<answer id="a2" label="test.q3.a2" points="10"/>
		<answer id="a3" label="test.q3.a3" points="0"/>
	</question>
	<question id="q4" label="test.q4">
		<answer id="a1" label="test.q4.a1" points="0"/>
		<answer id="a2" label="test.q4.a2" points="10"/>
		<answer id="a3" label="test.q4.a3" points="20"/>
	</question>
	<question id="q5" label="test.q5">
		<answer id="a1" label="test.q5.a1" points="20"/>
		<answer id="a2" label="test.q5.a2" points="0"/>
		<answer id="a3" label="test.q5.a3" points="-100"/>
	</question>
	<question id="q6" label="test.q6">
		<answer id="a1" label="test.q6.a1" points="20"/>
		<answer id="a2" label="test.q6.a2" points="10"/>
		<answer id="a3" label="test.q6.a3" points="0"/>
	</question>
	<question id="q7" label="test.q7">
		<answer id="a1" label="test.q7.a1" points="20"/>
		<answer id="a2" label="test.q7.a2" points="10"/>
		<answer id="a3" label="test.q7.a3" points="0"/>
	</question>
	<question id="q8" label="test.q8">
		<answer id="a1" label="test.q8.a1" points="10"/>
		<answer id="a2" label="test.q8.a2" points="20"/>
		<answer id="a3" label="test.q8.a3" points="0"/>
	</question>
</test>
