=== akarnokd/open-ig/trunk/open-ig-0.95.131/data/generic/schemas/walks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="walks">
		<xs:annotation>
			<xs:documentation>Definition of shipwalks for each level of ships.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ship" type="ship" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation><xs:documentation>A ship's layout definition.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ship">
		<xs:annotation><xs:documentation>A ship's layout definition.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="position" type="position" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>A position on the ship.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The level identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="ref" type="xs:int" use="optional">
			<xs:annotation><xs:documentation>The reference to another ship definition. If present, other properties are ignored.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="position">
		<xs:annotation><xs:documentation>A position on the ship.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="transition" type="transition" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The available transition definition.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>Position identifier. Identifiers starting with * refers to an actual game screen.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="picture" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The static picture of the position.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="transition">
		<xs:annotation><xs:documentation>The available transition definition.</xs:documentation></xs:annotation>
		<xs:attribute name="media" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The optional transition video.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The text label of the transition.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="area" type="xs:string" use="required">
			<xs:annotation><xs:documentation>Defines the polygon edges of the clickable area given by X,Y coordinate pairs separated by spaces. No space should precede or follow the comma.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="to" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The transition target position or screen (if starts with *).</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/walks.xml
<?xml version="1.0" encoding="UTF-8"?>
<walks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/walks.xsd">
	<ship id="1">
		<position id="*bridge" picture="flagship/bridge_level_1">
			<transition media="flagship/bridge_to_cabin_level_1" label="flagship.moveto.cabin" area="0,340 640,340 640,442 0,442" to="cabin"/>
			<transition media="" label="flagship.moveto.colony" area="237,221 431,221 431,300 237,300" to="*colony"/>
			<transition media="" label="flagship.moveto.starmap" area="45,155 199,161 227,134 393,134 420,160 573,155 577,241 432,240 432,220 236,220 236,240 41,240" to="*starmap"/>
			<transition media="" label="flagship.moveto.equipment2" area="214,64 400,64 400,112 214,112" to="*equipment"/>
			<transition media="" label="flagship.moveto.information" area="551,59 639,59 639,147 551,147" to="*information"/>
		</position>
		<position id="cabin" picture="flagship/cabin_level_1">
			<transition media="flagship/cabin_to_bridge_level_1" label="flagship.moveto.bridge" area="0,0 441,441 0,441" to="*bridge"/>
			<transition media="flagship/cabin_to_database_level_1" label="flagship.moveto.database" area="432,197 606,197 606,360 432,360" to="*database"/>
		</position>
	</ship>
	<ship id="2">
		<position id="*bridge" picture="flagship/bridge_level_2">
			<transition label="flagship.moveto.information" area="453,126 533,126 533,212 453,212" to="*information"/>
			<transition media="flagship/bridge_to_colony_level_2" label="flagship.moveto.colony" area="534,126 639,126 639,212 534,212" to="*colony"/>
			<transition label="flagship.moveto.equipment2" area="10,128 90,128 90,213 10,213" to="*equipment"/>
			<transition media="flagship/bridge_to_production_level_2" label="flagship.moveto.productionscreen" area="91,128 190,128 190,213 91,213" to="*production"/>
			<transition media="flagship/bridge_to_starmap_level_2" label="flagship.moveto.starmap" area="223,80 423,80 423,255 223,255" to="*starmap"/>
			<transition media="flagship/bridge_to_corridor_level_2" label="flagship.moveto.corridor" area="0,346 639,346 639,441 0,441" to="corridor_bridge"/>
		</position>
		<position id="corridor_bridge" picture="flagship/corridor_from_bridge_level_2">
			<transition media="flagship/corridor_to_bar_1_level_2" label="flagship.moveto.bar" area="511,34 639,34 639,386 511,386" to="*bar"/>
			<transition media="flagship/corridor_to_bridge_3_level_2" label="flagship.moveto.bridge" area="50,387 558,387 558,441 50,441" to="*bridge"/>
			<transition media="flagship/corridor_to_cabin_1_level_2" label="flagship.moveto.cabin" area="252,43 469,43 469,299 252,299" to="cabin"/>
		</position>
		<position id="cabin" picture="flagship/cabin_level_2">
			<transition media="flagship/cabin_to_database_level_2" label="flagship.moveto.database" area="439,139 602,139 602,302 439,302" to="*database"/>
			<transition media="flagship/cabin_to_corridor_level_2" label="flagship.moveto.corridor" area="90,327 563,327 563,441 90,441" to="corridor_cabin"/>
		</position>
		<position id="corridor_cabin" picture="flagship/corridor_from_cabin_level_2">
			<transition media="flagship/corridor_to_bridge_1_level_2" label="flagship.moveto.bridge" area="281,99 438,99 438,239, 99,239" to="*bridge"/>
			<transition media="flagship/corridor_to_bar_2_level_2" label="flagship.moveto.bar" area="0,0 156,0 156,441 0,441" to="*bar"/>
			<transition media="flagship/corridor_to_cabin_3_level_2" label="flagship.moveto.cabin" area="159,393 639,393 639,441 159,441" to="cabin"/>
		</position>
		<position id="corridor_bar" picture="flagship/corridor_from_bar_level_2">
			<transition media="flagship/corridor_to_bridge_2_level_2" label="flagship.moveto.bridge" area="0,0 72,0 72,398 0,398" to="*bridge"/>
			<transition media="flagship/corridor_to_cabin_2_level_2" label="flagship.moveto.cabin" area="526,0 639,0 639,408 526,408" to="cabin"/>
			<transition media="flagship/corridor_to_bar_3_level_2" label="flagship.moveto.bar" area="60,400 551,400 551,441 60,441" to="*bar"/>
		</position>
		<position id="*bar" picture="flagship/bar_level_2">
			<transition media="flagship/bar_to_corridor_level_2" label="flagship.moveto.corridor" area="0,356 639,356 639,441 0,441" to="corridor_bar"/>
		</position>
	</ship>
	<ship id="3">
		<position id="*bridge" picture="flagship/bridge_level_3">
			<transition media="flagship/bridge_to_production_level_3" label="flagship.moveto.production" area="0,115 103,115 103,294 0,294" to="production"/>
			<transition media="flagship/bridge_to_starmap_level_3" label="flagship.moveto.starmap" area="166,137 479,137 479,239 166,239" to="*starmap"/>
			<transition media="flagship/bridge_to_equipment_level_3" label="flagship.moveto.equipment" area="546,115 639,115 639,294 546,294" to="equipment"/>
			<transition media="" label="flagship.moveto.colony" area="168,314 137,433 487,433 456,314" to="*colony"/>
			<transition media="flagship/bridge_to_lift_level_3" label="flagship.moveto.lift" area="96,320 44,441 579,441 533,320 457,314 488,434 136,434 167,314" to="lift"/>
			<transition label="flagship.moveto.information" area="0,325 94,320 42,440 0,440" to="*information"/>
		</position>
		<position id="lift" picture="flagship/lift_level_3">
			<transition media="flagship/lift_to_bridge_level_3" label="flagship.moveto.bridge" area="0,342 639,342 639,441 0,441" to="*bridge"/>
			<transition media="flagship/lift_to_corridor_level_3" label="flagship.moveto.corridor" area="0,78 639,78 639,313 0,313" to="corridor1"/>
		</position>
		<position id="production" picture="flagship/production_level_3">
			<transition media="flagship/production_to_bridge_level_3" label="flagship.moveto.bridge" area="0,279 211,279 211,441 0,441" to="*bridge"/>
			<transition media="flagship/production_to_production_level_3" label="flagship.moveto.production" area="410,30 616,16 604,177 406,173" to="*production"/>
			<transition media="flagship/production_to_research_level_3" label="flagship.moveto.research" area="226,29 20,15 31,174 230,173" to="*research"/>
			<transition media="flagship/production_to_corridor_level_3" label="flagship.moveto.corridor" area="639,218 492,279 575,441 639,441" to="corridor2"/>
		</position>
		<position id="equipment" picture="flagship/equipment_level_3">
			<transition media="flagship/equipment_to_bridge_level_3" label="flagship.moveto.bridge" area="462,298 639,298 639,441 462,441" to="*bridge"/>
			<transition media="flagship/equipment_to_corridor_level_3" label="flagship.moveto.corridor" area="0,298 146,298 146,441 0,441" to="corridor3"/>
			<transition media="flagship/equipment_to_equipment_level_3" label="flagship.moveto.equipment" area="224,64 226,222 418,222 429,72" to="*equipment"/>
		</position>
		<position id="corridor1" picture="flagship/corridor_from_lift_level_3">
			<transition media="flagship/corridor_to_cabin_1_level_3" label="flagship.moveto.cabin" area="19,85 202,85 202,410 19,410" to="cabin"/>
			<!--			<transition media='flagship/corridor_to_diplomacy_1_level_4' label='flagship.moveto.diplomacy' area='461,112 606,112 606,411 461,441' to='*diplomacy'/>-->
			<transition media="flagship/corridor_to_bar_1_level_3" label="flagship.moveto.bar" area="261,183 376,183 376,273 261,273" to="*bar"/>
			<transition media="flagship/corridor_to_lift_1_level_3" label="flagship.moveto.lift" area="0,411 639,411 639,441 0,441" to="lift"/>
		</position>
		<position id="corridor2" picture="flagship/corridor_left_window_level_3">
			<transition media="flagship/corridor_to_window_2_level_3" label="flagship.moveto.window" area="0,26 91,26 91,329 0,329" to="window"/>
			<transition media="flagship/corridor_to_equipment_2_level_3" label="flagship.moveto.equipment" area="211,153 421,153 421,316 211,316" to="equipment"/>
			<transition media="flagship/corridor_to_production_1_level_3" label="flagship.moveto.production" area="0,390 639,390 639,441 0,441" to="production"/>
		</position>
		<position id="corridor3" picture="flagship/corridor_right_window_level_3">
			<transition media="flagship/corridor_to_window_1_level_3" label="flagship.moveto.window" area="540,37 639,37 639,334 540,334" to="window"/>
			<transition media="flagship/corridor_to_equipment_1_level_3" label="flagship.moveto.equipment" area="0,360 639,360 639,441 0,441" to="equipment"/>
			<transition media="flagship/corridor_to_production_3_level_3" label="flagship.moveto.production" area="229,154 427,154 427,315 229,315" to="production"/>
		</position>
		<position id="window" picture="flagship/corridor_window_level_3">
			<transition media="flagship/corridor_to_equipment_3_level_3" label="flagship.moveto.equipment" area="490,0 639,0 639,441 490,441" to="equipment"/>
			<transition media="flagship/corridor_to_production_2_level_3" label="flagship.moveto.production" area="0,0 150,0 150,441 0,441" to="production"/>
		</position>
		<position id="*bar" picture="flagship/bar_level_3">
			<transition media="flagship/bar_to_corridor_level_3" label="flagship.moveto.corridor" area="0,356 639,356 639,441 0,441" to="bar_front"/>
		</position>
		<position id="bar_front" picture="flagship/corridor_lift_opposite_level_3">
			<transition media="flagship/corridor_to_bar_4_level_3" label="flagship.moveto.bar" area="257,350 509,350 509,441 257,441" to="*bar"/>
			<transition media="flagship/corridor_to_cabin_4_level_3" label="flagship.moveto.cabin" area="510,141 639,141 639,416 510,416" to="cabin"/>
			<!--			<transition media='flagship/corridor_to_diplomacy_4_level_4' label='flagship.moveto.diplomacy' area='0,79 129,79 129,421 0,421' to='*diplomacy'/>-->
			<transition media="flagship/corridor_to_lift_4_level_3" label="flagship.moveto.lift" area="256,173 385,173 385,291 256,291" to="lift"/>
		</position>
		<position id="cabin" picture="flagship/cabin_level_3">
			<transition media="flagship/cabin_to_database_level_3" label="flagship.moveto.database" area="56,256 130,256 130,330 56,330" to="*database"/>
