=== akarnokd/open-ig/open-ig-0.95/data/generic/schemas/diplomacy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="diplomacy" type="diplomacy">
		<xs:annotation>
			<xs:documentation>Describes the diplomatic options and stance changes available to the player and AI.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="diplomacy">
		<xs:annotation><xs:documentation>The list of players which the player can have interactions with.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="player" type="player" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The diplomatic option with a single AI player.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="player">
		<xs:annotation><xs:documentation>The diplomatic option with a single AI player.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="negotiate" type="negotiate" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>Description of the outgoing negotiations.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="terminate" type="xs:string">
				<xs:annotation><xs:documentation>The label used to say the termination of the negotiation.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="call" type="call" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The incoming negotiation settings from this player.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The identifier of the player as specified in the players.xml .</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="negotiate">
		<xs:annotation><xs:documentation>The definition of a negotiation topic.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="approach" type="approach" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>Definition the approach or tone of the negotiation.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="response" type="response" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>Definition of the possible responses to the approaches.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The negotiation type enumeration. See hu.openig.model.NegotiateType enumeration.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="approach">
		<xs:annotation><xs:documentation>The diplomatic approach definition. The content points to the label to display.</xs:documentation></xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="xs:string" use="required">
					<xs:annotation><xs:documentation>The approach strength. See hu.openig.model.ApproachType enumeration.</xs:documentation></xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="response">
		<xs:annotation><xs:documentation>The response definition. The content points to the label to display.</xs:documentation></xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="xs:string" use="required">
					<xs:annotation><xs:documentation>The response strength. See hu.openig.model.ApproachType enumeration.</xs:documentation></xs:annotation>
				</xs:attribute>
				<xs:attribute name="mode" type="xs:string" use="required">
					<xs:annotation><xs:documentation>Defines the negotiations general acceptance. See hu.openig.model.ResponseMode enumeration.</xs:documentation></xs:annotation>
				</xs:attribute>
				<xs:attribute name="change" type="xs:integer" use="required">
					<xs:annotation><xs:documentation>The numerical change in the stance between the player and the target player.</xs:documentation></xs:annotation>
				</xs:attribute>
				<xs:attribute name="notalk" type="xs:boolean" use="optional">
					<xs:annotation><xs:documentation>Indication if this outcome will not let any further negotiation take place for a while.</xs:documentation></xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="call">
		<xs:annotation><xs:documentation>The list of approaches available to the target player.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="approach" type="call-approach" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The call approach definition.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The call type. See hu.openig.model.NegotiateType enumeration.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="call-approach">
		<xs:annotation><xs:documentation>The call approach definition.</xs:documentation></xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" type="xs:string" use="required">
					<xs:annotation><xs:documentation>The response strength. See hu.openig.model.ApproachType enumeration.</xs:documentation></xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/data/generic/campaign/main/diplomacy.xml
<?xml version='1.0' encoding='UTF-8'?>
<diplomacy noNamespaceSchemaLocation='../../schemas/diplomacy.xsd'>
  <player id='FreeNations'>
    <negotiate type='DIPLOMATIC_RELATIONS'>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.1</approach>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.2</approach>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.3</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.4</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.5</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.6</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.HUMBLE.7</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.HUMBLE.8</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.HUMBLE.9</approach>
      <response type='AGGRESSIVE' mode='YES' change='150'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.10</response>
      <response type='AGGRESSIVE' mode='YES' change='120'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.11</response>
      <response type='AGGRESSIVE' mode='YES' change='100'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.12</response>
      <response type='AGGRESSIVE' mode='MAYBE' change='-80'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.13</response>
      <response type='AGGRESSIVE' mode='MAYBE' change='-70'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.14</response>
      <response type='AGGRESSIVE' mode='MAYBE' change='-50'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.15</response>
      <response type='AGGRESSIVE' mode='NO' notalk='true' change='-150'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.16</response>
      <response type='AGGRESSIVE' mode='NO' notalk='true' change='-250'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.17</response>
      <response type='AGGRESSIVE' mode='NO' notalk='true' change='-270'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.18</response>
      <response type='NEUTRAL' mode='YES' change='160'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.YES.19</response>
      <response type='NEUTRAL' mode='YES' change='150'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.YES.20</response>
      <response type='NEUTRAL' mode='YES' change='140'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.YES.21</response>
      <response type='NEUTRAL' mode='MAYBE' change='0'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.MAYBE.22</response>
      <response type='NEUTRAL' mode='MAYBE' change='0'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.MAYBE.23</response>
      <response type='NEUTRAL' mode='MAYBE' change='0'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.MAYBE.24</response>
      <response type='NEUTRAL' mode='NO' change='-100'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.NO.25</response>
      <response type='NEUTRAL' mode='NO' change='-120'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.NO.26</response>
      <response type='NEUTRAL' mode='NO' change='-150'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.NO.27</response>
      <response type='HUMBLE' mode='YES' change='80'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.28</response>
      <response type='HUMBLE' mode='YES' change='60'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.29</response>
      <response type='HUMBLE' mode='YES' change='50'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.30</response>
      <response type='HUMBLE' mode='MAYBE' notalk='true' change='-50'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.31</response>
      <response type='HUMBLE' mode='MAYBE' notalk='true' change='-50'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.32</response>
      <response type='HUMBLE' mode='MAYBE' notalk='true' change='-50'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.33</response>
      <response type='HUMBLE' mode='NO' notalk='true' change='-200'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.34</response>
      <response type='HUMBLE' mode='NO' notalk='true' change='-200'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.35</response>
      <response type='HUMBLE' mode='NO' notalk='true' change='-200'>diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.36</response>
    </negotiate>
    <negotiate type='MONEY'>
      <approach type='NEUTRAL'>diplomacy.FreeNations.MONEY.37</approach>
      <response type='NEUTRAL' mode='YES' change='120'>diplomacy.FreeNations.MONEY.YES.38</response>
      <response type='NEUTRAL' mode='YES' change='80'>diplomacy.FreeNations.MONEY.YES.39</response>
      <response type='NEUTRAL' mode='YES' change='60'>diplomacy.FreeNations.MONEY.YES.40</response>
      <response type='NEUTRAL' mode='NO' notalk='true' change='-50'>diplomacy.FreeNations.MONEY.NO.41</response>
      <response type='NEUTRAL' mode='NO' notalk='true' change='-100'>diplomacy.FreeNations.MONEY.NO.42</response>
      <response type='NEUTRAL' mode='NO' notalk='true' change='-150'>diplomacy.FreeNations.MONEY.NO.43</response>
    </negotiate>
    <negotiate type='TRADE'>
      <approach type='NEUTRAL'>diplomacy.FreeNations.TRADE.44</approach>
      <response type='NEUTRAL' mode='YES' change='150'>diplomacy.FreeNations.TRADE.YES.45</response>
      <response type='NEUTRAL' mode='YES' change='130'>diplomacy.FreeNations.TRADE.YES.46</response>
      <response type='NEUTRAL' mode='YES' change='110'>diplomacy.FreeNations.TRADE.YES.47</response>
      <response type='NEUTRAL' mode='NO' change='0'>diplomacy.FreeNations.TRADE.NO.48</response>
      <response type='NEUTRAL' mode='NO' change='-20'>diplomacy.FreeNations.TRADE.NO.49</response>
      <response type='NEUTRAL' mode='NO' change='-20'>diplomacy.FreeNations.TRADE.NO.50</response>
    </negotiate>
    <negotiate type='ALLY'>
      <approach type='NEUTRAL'>diplomacy.FreeNations.ALLY.51</approach>
      <response type='NEUTRAL' mode='YES' change='150'>diplomacy.FreeNations.ALLY.YES.52</response>
      <response type='NEUTRAL' mode='YES' change='120'>diplomacy.FreeNations.ALLY.YES.53</response>
      <response type='NEUTRAL' mode='YES' change='100'>diplomacy.FreeNations.ALLY.YES.54</response>
      <response type='NEUTRAL' mode='NO' change='-40'>diplomacy.FreeNations.ALLY.NO.55</response>
      <response type='NEUTRAL' mode='NO' change='-50'>diplomacy.FreeNations.ALLY.NO.56</response>
      <response type='NEUTRAL' mode='NO' change='-90'>diplomacy.FreeNations.ALLY.NO.57</response>
    </negotiate>
    <negotiate type='DARGSLAN'>
      <approach type='NEUTRAL'>diplomacy.FreeNations.DARGSLAN.58</approach>
      <response type='NEUTRAL' mode='YES' change='200'>diplomacy.FreeNations.DARGSLAN.YES.59</response>
      <response type='NEUTRAL' mode='YES' change='180'>diplomacy.FreeNations.DARGSLAN.YES.60</response>
      <response type='NEUTRAL' mode='YES' change='160'>diplomacy.FreeNations.DARGSLAN.YES.61</response>
      <response type='NEUTRAL' mode='NO' change='0'>diplomacy.FreeNations.DARGSLAN.NO.62</response>
      <response type='NEUTRAL' mode='NO' change='0'>diplomacy.FreeNations.DARGSLAN.NO.63</response>
      <response type='NEUTRAL' mode='NO' change='0'>diplomacy.FreeNations.DARGSLAN.NO.64</response>
    </negotiate>
    <negotiate type='SURRENDER'>
      <approach type='NEUTRAL'>diplomacy.FreeNations.SURRENDER.65</approach>
      <response type='NEUTRAL' mode='YES' notalk='true' change='0'>diplomacy.FreeNations.SURRENDER.YES.66</response>
      <response type='NEUTRAL' mode='YES' notalk='true' change='0'>diplomacy.FreeNations.SURRENDER.YES.67</response>
      <response type='NEUTRAL' mode='YES' notalk='true' change='0'>diplomacy.FreeNations.SURRENDER.YES.68</response>
      <response type='NEUTRAL' mode='NO' notalk='true' change='-200'>diplomacy.FreeNations.SURRENDER.NO.69</response>
      <response type='NEUTRAL' mode='NO' notalk='true' change='-200'>diplomacy.FreeNations.SURRENDER.NO.70</response>
      <response type='NEUTRAL' mode='NO' notalk='true' change='-200'>diplomacy.FreeNations.SURRENDER.NO.71</response>
    </negotiate>
    <terminate>diplomacy.FreeNations.terminate.72</terminate>
    <call type='SURRENDER'>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.SURRENDER.73</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.SURRENDER.74</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.SURRENDER.75</approach>
    </call>
    <call type='ALLIANCE'>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.ALLIANCE.76</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.ALLIANCE.77</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.ALLIANCE.78</approach>
    </call>
    <call type='PEACE'>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.PEACE.79</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.PEACE.80</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.PEACE.81</approach>
    </call>
    <call type='MONEY'>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.MONEY.82</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.MONEY.83</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.MONEY.84</approach>
    </call>
    <call type='WAR'>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.WAR.85</approach>
      <approach type='NEUTRAL'>diplomacy.FreeNations.WAR.86</approach>
      <approach type='HUMBLE'>diplomacy.FreeNations.WAR.87</approach>
    </call>
    <call type='RESIGN'>
      <approach type='AGGRESSIVE'>diplomacy.FreeNations.RESIGN.88</approach>
