=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="buildings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name='race'>
					<xs:complexType>
						<xs:sequence>
							<xs:element name='building' maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name='graphics'>
											<xs:complexType>
												<xs:sequence>
													<xs:element name='normal' type='xs:string'></xs:element>
													<xs:element name='damaged' type='xs:string'></xs:element>
													<xs:element name='mini' type='xs:string'></xs:element>
													<xs:element name='width' type="xs:positiveInteger"></xs:element>
													<xs:element name='height' type='xs:positiveInteger'></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name='build'>
											<xs:complexType>
												<xs:sequence>
													<xs:element name='cost' type="xs:nonNegativeInteger"></xs:element>
													<xs:element name='kind' type="xs:string"></xs:element>
													<xs:element name='limit' type='xs:string'></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name='operation'>
											<xs:complexType>
												<xs:sequence>
													<xs:element name='unit' maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:double">
																	<xs:attribute name='type' type='xs:string'
																		use="required"></xs:attribute>
																	<xs:attribute name='display' type='xs:boolean'
																		use="optional"></xs:attribute>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name='upgrades'>
											<xs:complexType>
												<xs:sequence>
													<xs:element name='upgrade' minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name='unit' maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:double">
																				<xs:attribute name='type' type='xs:string'
																					use="required"></xs:attribute>
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name='desc'></xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name='id' type='xs:string'></xs:attribute>
									<xs:attribute name='label' type='xs:string'></xs:attribute>
									<xs:attribute name='desc' type='xs:string'></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name='id' type='xs:string'></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/buildings.xml
<?xml version='1.0' encoding='UTF-8'?>
<buildings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="buildings.xsd">
	<building id='ColonyHub' label='buildings.colony_hub'>
		<graphics base="colony/buildings/%s/colony_hub">
			<race id='human' width="8" height="7"/>
			<race id="2" height="6" width="3"/>
			<race id="3" height="5" width="6"/>
			<race id="4" height="3" width="3"/>
			<race id="5" height="4" width="4"/>
			<race id="6" height="3" width="4"/>
			<race id="7" height="8" width="5"/>
			<race id="8" height="4" width="4"/>
		</graphics>
		<build cost="40000" kind="MainBuilding" limit="1"/> 
		<operation>
			<unit type='energy'>0</unit>
			<unit type='worker'>-960</unit>
			<unit type='food'>5000</unit>
			<unit type='hospital'>10000</unit>
		</operation>	
		<upgrades>
		</upgrades>		
	</building>
	<building id='PrefabHousing' label='buildings.prefab_housing'>
		<graphics base="colony/buildings/%s/prefab_housing">
			<race id='human' width="4" height="3"/>
		</graphics>
		<build cost="5600" kind="House" limit="*"/>
		<operation>
			<unit type='energy'>-850</unit>
			<unit type='worker'>-60</unit>
			<unit type='house' display='true'>7000</unit>
		</operation>
		<upgrades>
			<upgrade desc='buildings.housing.upgrade_1'>
				<unit type='house'>1.25</unit>
				<unit type='energy'>1.25</unit>
				<unit type='worker'>1.25</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_2'>
				<unit type='house'>1.5</unit>
				<unit type='energy'>1.5</unit>
				<unit type='worker'>1.5</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_3'>
				<unit type='house'>2</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_4'>
				<unit type='house'>2.5</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
		</upgrades>
	</building>
	<building id="ApartmentBlock" label="buildings.apartment_block">
		<graphics base='colony/buildings/%s/apartment_block'>
			<race id='human' width='4' height='3'/>
		</graphics>
		<build cost='12000' kind='House' limit='*'/>
		<operation>
			<unit type="house" display="true">15000</unit>
			<unit type="energy">-1200</unit>
			<unit type="worker">-70</unit>
		</operation>
		<upgrades>
			<upgrade desc='buildings.housing.upgrade_1'>
				<unit type='house'>1.25</unit>
				<unit type='energy'>1.25</unit>
				<unit type='worker'>1.25</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_2'>
				<unit type='house'>1.5</unit>
				<unit type='energy'>1.5</unit>
				<unit type='worker'>1.5</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_3'>
				<unit type='house'>2</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_4'>
				<unit type='house'>2.5</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
		</upgrades>
	</building>
	<building label="buildings.arcology" id="Arcology">
		<graphics base="colony/buildings/%s/arcology">
			<race id='human' height="4" width="3"></race>
			<race id="2" height="2" width="3"/>
			<race id="3" height="4" width="2"/>
			<race id="4" height="3" width="3"/>
			<race id="5" height="3" width="2"/>
			<race id="6" height="2" width="2"/>
			<race id="7" height="2" width="3"/>
			<race id="8" height="3" width="2"/>
		</graphics> 
		<build limit="*" kind="House" cost="16000"/>
		<operation>
			<unit type="house" display="true">30000</unit>
			<unit type="energy">-1500</unit>
			<unit type="worker">-100</unit>
		</operation>
		<upgrades>
			<upgrade desc='buildings.housing.upgrade_1'>
				<unit type='house'>1.25</unit>
				<unit type='energy'>1.25</unit>
				<unit type='worker'>1.25</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_2'>
				<unit type='house'>1.5</unit>
				<unit type='energy'>1.5</unit>
				<unit type='worker'>1.5</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_3'>
				<unit type='house'>2</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_4'>
				<unit type='house'>2.5</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
		</upgrades>
	</building>
	<building label="buildings.nuclear_plant" id="NuclearPlant">
		<graphics base="colony/buildings/%s/nuclear_plant">
			<race height="5" width="5" id="human"/>
			<race id="2" height="3" width="3"/>
			<race id="3" height="3" width="3"/>
			<race id="4" height="4" width="4"/>
			<race id="5" height="5" width="4"/>
			<race id="6" height="4" width="4"/>
			<race id="7" height="5" width="4"/>
			<race id="8" height="3" width="4"/>
		</graphics>
		<build limit="*" kind="Power" cost="8000"/>
		<operation percent="true">
			<unit type='energy' display="true">3500</unit>
			<unit type="worker">-290</unit>
		</operation>
		<upgrades>
			<upgrade desc="buildings.power.upgrade_1">
				<unit type="energy">1.5</unit>
				<unit type='worker'>1.25</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_2">
				<unit type="energy">2</unit>
				<unit type='worker'>1.5</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_3">
				<unit type="energy">2.5</unit>
				<unit type='worker'>2</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_4">
				<unit type="energy">3</unit>
				<unit type='worker'>2</unit>
			</upgrade>
		</upgrades>
	</building>
	<building label="buildings.fusion_plant" id="FusionPlanet">
		<graphics base="colony/buildings/%s/fusion_plant">
			<race height="5" width="5" id="human"/>
		</graphics>
		<build limit="*" kind="Power" cost="24000" except='Desert,Neptoplasm,Rocky'/>
		<operation percent="true">
			<unit type='energy' display="true">9000</unit>
			<unit type="worker">-500</unit>
		</operation>
		<upgrades>
			<upgrade desc="buildings.power.upgrade_1">
				<unit type="energy">1.5</unit>
				<unit type='worker'>1.25</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_2">
				<unit type="energy">2</unit>
				<unit type='worker'>1.5</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_3">
				<unit type="energy">2.5</unit>
				<unit type='worker'>2</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_4">
				<unit type="energy">3</unit>
				<unit type='worker'>2</unit>
			</upgrade>
		</upgrades>			
	</building>
	<building label="buildings.solar_plant" id="SolarPlant">
		<graphics base="colony/buildings/%s/solar_plant">
			<race id='human' height="5" width="5"/>
		</graphics>
		<build limit="*" kind="Power" cost="16000" except="Frozen,Liquid" research="SolarPlant"/>
		<operation percent="true">
			<unit type='energy' display="true">6000</unit>
			<unit type='worker'>-350</unit>
		</operation>
		<upgrades>
			<upgrade desc="buildings.power.upgrade_1">
				<unit type="energy">1.5</unit>
				<unit type='worker'>1.25</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_2">
				<unit type="energy">2</unit>
				<unit type='worker'>1.5</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_3">
				<unit type="energy">2.5</unit>
				<unit type='worker'>2</unit>
			</upgrade>
			<upgrade desc="buildings.power.upgrade_4">
				<unit type="energy">3</unit>
				<unit type='worker'>2</unit>
			</upgrade>
		</upgrades>			
	</building>
	<building label="buildings.water_vaporator" id="WaterVaporator">
		<graphics base="colony/buildings/%s/water_vaporator">
			<race id='human' height="5" width="5"/>
		</graphics>
		<build limit="*" kind="House" cost="45000" except="Earth,Frozen,Liquid,Rocky"/>
		<operation>
			<unit type="house" display="true">12000</unit>
			<unit type="energy">-800</unit>
			<unit type="worker">-210</unit>
		</operation>
		<upgrades>
			<upgrade desc='buildings.housing.upgrade_1'>
				<unit type='house'>1.25</unit>
				<unit type='energy'>1.25</unit>
				<unit type='worker'>1.25</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_2'>
				<unit type='house'>1.5</unit>
				<unit type='energy'>1.5</unit>
				<unit type='worker'>1.5</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_3'>
				<unit type='house'>2</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
			<upgrade desc='buildings.housing.upgrade_4'>
				<unit type='house'>2.5</unit>
				<unit type='energy'>2</unit>
				<unit type='worker'>1.75</unit>
			</upgrade>
		</upgrades>
	</building>
	<building label="buildings.hydroponic_food_farm" id="HydroponicFoodFarm">
		<graphics base="colony/buildings/%s/hydroponic_food_farm">
			<race id='human' height="5" width="3"/>
		</graphics>
		<build limit="*" kind="Food" cost="4200"/>
		<operation>
			<unit type="food" display="true">8000</unit>
			<unit type="energy">-1300</unit>
			<unit type='worker'>-300</unit>
		</operation>
		<upgrades>
			<upgrade desc="buildings.food.upgrade_1">
				<unit type="food">1.25</unit>
				<unit type="energy">1.25</unit>
				<unit type="worker">1.25</unit>
			</upgrade>
			<upgrade desc="buildings.food.upgrade_2">
				<unit type="food">1.5</unit>
				<unit type="energy">1.5</unit>
				<unit type="worker">1.5</unit>
			</upgrade>
			<upgrade desc="buildings.food.upgrade_3">
				<unit type="food">2</unit>
				<unit type="energy">2</unit>
				<unit type="worker">2</unit>
			</upgrade>
			<upgrade desc="buildings.food.upgrade_4">
				<unit type="food">2.5</unit>
				<unit type="energy">2</unit>
				<unit type="worker">2</unit>
			</upgrade>
		</upgrades>
	</building>
	<building label="buildings.phood_factory" id="PhoodFactory">
		<graphics base="colony/buildings/%s/phood_factory">
