=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/talks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by karnokd (EMBRACE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="talks">
		<xs:annotation>
			<xs:documentation>The list of talks.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="talk" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>A talk with somebody.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="state" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The talk state.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="transition" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>The transition.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="media" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>The associated media path and identifier (refers to video, audio or just picture).</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="text" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>The label to display as a selection option.</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="to" type="xs:string" use="required">
													<xs:annotation>
														<xs:documentation>The next state identifier</xs:documentation>
													</xs:annotation>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>The state identifier. Used in the transition to attribute.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="picture" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>The static picture to show as background in this state.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="with" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>The talk identifier.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig-0.95.131/data/generic/campaign/main/talks.xml
<?xml version="1.0" encoding="UTF-8"?>
<talks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/talks.xsd">
	<!-- Talk graphs in the bar -->
	<talk with="phsychologist">
		<state id="start" picture="bar/phsychologist_100">
			<transition id="101" media="bar/phsychologist_101" text="bar.phsychologist.101" to="state101"/>
		</state>
		<state id="state101" picture="bar/phsychologist_101">
			<transition id="111" media="bar/phsychologist_111" text="bar.phsychologist.111" to="state101"/>
			<transition id="112" media="bar/phsychologist_112" text="bar.phsychologist.112" to="state101"/>
			<transition id="121" media="bar/phsychologist_121" text="bar.phsychologist.121" to="end"/>
		</state>
	</talk>
	<talk with="kelly">
		<state id="start" picture="bar/kelly_000">
			<transition id="001" media="bar/kelly_001" text="bar.kelly.001" to="state001"/>
		</state>
		<state id="state001" picture="bar/kelly_001">
			<transition id="011" media="bar/kelly_011" text="bar.kelly.011" to="state011"/>
		</state>
		<state id="state011" picture="bar/kelly_011">
			<transition id="021" media="bar/kelly_021" text="bar.kelly.021" to="state021"/>
			<transition id="041" media="bar/kelly_041" text="bar.kelly.041" to="end"/>
		</state>
		<state id="state021" picture="bar/kelly_021">
			<transition id="022" media="bar/kelly_022" text="bar.kelly.022" to="state032"/>
			<transition id="041" media="bar/kelly_041" text="bar.kelly.041" to="end"/>
		</state>
		<state id="state032" picture="bar/kelly_032">
			<transition id="032" media="bar/kelly_032" text="bar.kelly.032" to="state041"/>
			<transition id="041" media="bar/kelly_041" text="bar.kelly.041" to="end"/>
		</state>
		<state id="state041" picture="bar/kelly_041">
			<transition id="041" media="bar/kelly_041" text="bar.kelly.041" to="end"/>
		</state>
	</talk>
	<talk with="brian">
		<state id="start" picture="bar/brian_300">
			<transition id="301" media="bar/brian_301" text="bar.brian.301" to="state301"/>
		</state>
		<state id="state301" picture="bar/brian_301">
			<transition id="311" media="bar/brian_311" text="bar.brian.311" to="state311"/>
			<transition id="312" media="bar/brian_312" text="bar.brian.312" to="state312"/>
		</state>
		<state id="state311" picture="bar/brian_311">
			<transition id="321" media="bar/brian_321" text="bar.brian.321" to="state311"/>
			<transition id="323" media="bar/brian_323" text="bar.brian.323" to="state311"/>
			<transition id="331" media="bar/brian_331" text="bar.brian.331" to="end"/>
		</state>
		<state id="state312" picture="bar/brian_312">
			<transition id="331" media="bar/brian_331" text="bar.brian.331" to="end"/>
		</state>
	</talk>
	<talk with="doctor">
		<state id="start" picture="bar/doctor_400">
			<transition id="401" media="bar/doctor_401" text="bar.doctor.401" to="state401"/>
			<transition id="402" media="bar/doctor_402" text="bar.doctor.402" to="state402"/>
		</state>
		<state id="state401" picture="bar/doctor_401">
			<transition id="411" media="bar/doctor_411" text="bar.doctor.411" to="state410"/>
		</state>
		<state id="state402" picture="bar/doctor_402">
			<transition id="412" media="bar/doctor_412" text="bar.doctor.412" to="state410"/>
		</state>
		<state id="state410" picture="bar/doctor_411">
			<transition id="421" media="bar/doctor_421" text="bar.doctor.421" to="state421"/>
		</state>
		<state id="state421" picture="bar/doctor_421">
			<transition id="431" media="bar/doctor_431" text="bar.doctor.431" to="state431"/>
		</state>
		<state id="state431" picture="bar/doctor_431">
			<transition id="441" media="bar/doctor_441" text="bar.doctor.441" to="state441"/>
		</state>
		<state id="state441" picture="bar/doctor_441">
			<transition id="451" media="bar/doctor_451" text="bar.doctor.451" to="end"/>
		</state>
	</talk>
</talks>
