=== akarnokd/open-ig/data/generic/schemas/galaxy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="galaxy">
		<xs:annotation>
			<xs:documentation>Defines the tile sizes for various surface types and the population growth per surface type.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="background">
					<xs:annotation><xs:documentation>The galaxy background image and zoom limits.</xs:documentation></xs:annotation>
					<xs:complexType>
						<xs:attribute name="min-scale" type="positiveReal" use="required">
							<xs:annotation><xs:documentation>The minimum scale for the image as a background.</xs:documentation></xs:annotation>
						</xs:attribute>
						<xs:attribute name="max-scale" type="positiveReal" use="required">
							<xs:annotation><xs:documentation>The maximum scale for the image as a background</xs:documentation></xs:annotation>
						</xs:attribute>
						<xs:attribute name="image" type="xs:string" use="required">
							<xs:annotation><xs:documentation>The resource path of the background image (without extension).</xs:documentation></xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="planets">
					<xs:annotation><xs:documentation>The list of planet types and their tile sizes.</xs:documentation></xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="planet" minOccurs="1" maxOccurs="unbounded" type="planet">
								<xs:annotation><xs:documentation>The definition of a concrete planet type.</xs:documentation></xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="population-growths" type="population-growths">
					<xs:annotation><xs:documentation>The list of planet-type vs race growth rates. Any unmentioned combination is considered to be 1.0</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="planet-naming" type="planet-naming" minOccurs="0">
					<xs:annotation><xs:documentation>A list of names usable when generating random galaxies.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="positiveReal">
		<xs:annotation><xs:documentation>A positive real number.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="planet">
		<xs:annotation><xs:documentation>Definition of the planet tiles of a particular type.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="body" type="xs:string">
				<xs:annotation><xs:documentation>The image for the starmap screen, should contain multiple rotation phases. The number of animation items is width / height.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="equipment" type="xs:string">
				<xs:annotation><xs:documentation>The planet's image on the equipment screen.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="spacewar" type="xs:string">
				<xs:annotation><xs:documentation>The planet's image on the spacewar screen.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="tileset" type="tileset">
				<xs:annotation><xs:documentation>The size definitions of the tiles used by this planet type.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="map" type="map">
				<xs:annotation><xs:documentation>The resource location and pattern for surface map variations.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="weather" type="weather" minOccurs="0" maxOccurs="1">
				<xs:annotation><xs:documentation>The optional weather definition. If absent, no weather effects are rendered.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The planet type.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label of the planet type.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="weather">
		<xs:annotation><xs:documentation>The optional weather definition. If absent, no weather effects are rendered.</xs:documentation></xs:annotation>
		<xs:attribute name="frequency" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The weather effect frequency in game minutes.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="duration" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The weather effect duration in game minutes.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="drop-type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The drop type, see WeatherType enum.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="tileset">
		<xs:annotation><xs:documentation>The size definitions of the tiles used by this planet type.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="tile-range" type="tile-range">
					<xs:annotation><xs:documentation>A tile range definition where each tile has the same dimensions.</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="tile" type="tile">
					<xs:annotation><xs:documentation>A concrete tile definition.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="pattern" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The resource location pattern, usually containing a single %d which is substituted by real indexes from the child element definitions. For example: "map/tile_%03d". Usage of Java format specifiers is possible.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="map">
		<xs:annotation><xs:documentation>The resource location and pattern for surface map variations.</xs:documentation></xs:annotation>
		<xs:attribute name="pattern" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The resource path to the map variations, usually containing a single %d, e.g., "map/surface_type_%d".</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="start" type="xs:int" use="required">	
			<xs:annotation><xs:documentation>The start index used for enumerating the map variations referenced by the pattern attribute.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="end" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The end index (inclusive) used for enumerating the map variations referenced by the pattern attribute.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="tile-range">
		<xs:annotation><xs:documentation>A tile range definition where each tile has the same dimensions.</xs:documentation></xs:annotation>
		<xs:attributeGroup ref="width-height"/>
		<xs:attribute name="start" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The start index of the tile, used for enumerating the tile images.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="end" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The end index (inclusive) of the tile, used for enumerating the tile images.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="tile">
		<xs:annotation><xs:documentation>A concrete tile definition.</xs:documentation></xs:annotation>
		<xs:attributeGroup ref="width-height"/>
		<xs:attribute name="id" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The index of the tile, used for enumerating the tile images.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:attributeGroup name="width-height">
		<xs:annotation><xs:documentation>The width and height attributes.</xs:documentation></xs:annotation>
		<xs:attribute name="width" type="xs:positiveInteger" use="optional" default="1">
			<xs:annotation><xs:documentation>The tile width, which points slightly right and up.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="height" type="xs:positiveInteger" use="optional" default="1">
			<xs:annotation><xs:documentation>The tile height, which points slightly right and down.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:complexType name="population-growths">
		<xs:annotation><xs:documentation>The planet growths for planet type and race.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="growth" type="growth" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The growth scale for a planet type and race pairs.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="growth">
		<xs:annotation><xs:documentation>The growth scale for a planet type and race pairs.</xs:documentation></xs:annotation>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The planet type identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="race" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The race name, as used by the player and technology.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="nonzero" use="required">
			<xs:annotation><xs:documentation>The growth multiplier.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="nonzero">
		<xs:annotation><xs:documentation>A greater than zero decimal value.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="planet-naming">
		<xs:annotation><xs:documentation>A list of names usable when generating random galaxies.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="single" type="labeled-name" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>Indicates a name that may appear only once in the galaxy</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="multiple" type="labeled-name" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>Indicates a name that may appear multiple times in the galaxy</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="labeled-name">
		<xs:annotation><xs:documentation>A string content with an optional label attribute</xs:documentation></xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="label" type="xs:string" use="optional">
					<xs:annotation><xs:documentation>If present, this indicates the name should be localized under this label.</xs:documentation></xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>					
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/galaxy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- The description of the galactic entities -->
<galaxy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/galaxy.xsd">
	<background min-scale="0.5" max-scale="4" image="starmap/background"/>
	<planets>
		<planet type="neptoplasm" label="planet.type.neptoplasm">
			<body>starmap/planets/planet_alien_30x30</body>
			<equipment>colony/surfaces/neptoplasm/equipment_neptoplasm</equipment>
			<spacewar>colony/surfaces/neptoplasm/spacewar_neptoplasm</spacewar>
			<tileset pattern="colony/surfaces/neptoplasm/tile_neptoplasm_%03d">
				<tile-range start="21" end="26"/>
				<!-- width is the up-right and height is the down-right direction. -->
				<tile-range start="27" end="42" width="2" height="2"/>
				<tile id="43" width="3" height="2"/>
				<tile id="44" width="2" height="3"/>
				<tile id="45" width="3" height="3"/>
				<tile id="46" width="2" height="3"/>
				<tile id="47" width="2" height="3"/>
				<tile id="48" width="2" height="3"/>
				<tile-range start="49" end="57" width="4" height="4"/>
			</tileset>
			<map pattern="campaign/main/surfaces/neptoplasm_%d" start="1" end="6"/>
			<weather frequency='2880' duration='180' drop-type='RAIN'/>
		</planet>
		<planet type="cratered" label="planet.type.cratered">
			<body>starmap/planets/planet_cratered_30x30</body>
			<equipment>colony/surfaces/cratered/equipment_cratered</equipment>
			<spacewar>colony/surfaces/cratered/spacewar_cratered</spacewar>
			<tileset pattern="colony/surfaces/cratered/tile_cratered_%03d">
				<tile-range start="21" end="60"/>
				<tile id="61" width="2"/>
				<tile id="62" height="2"/>
				<tile-range start="63" end="86" width="2" height="2"/>
				<tile-range start="87" end="89" width="3" height="2"/>
				<tile id="90" width="4" height="2"/>
				<tile id="91" width="2" height="3"/>
				<tile-range start="92" end="94" width="3" height="3"/>
				<tile id="95" width="4" height="3"/>
				<tile id="96" width="2" height="4"/>
				<tile id="97" width="4" height="4"/>
			</tileset>
			<map pattern="campaign/main/surfaces/cratered_%d" start="1" end="9"/>
			<weather frequency='4320' duration='120' drop-type='SNOW'/>
		</planet>
		<planet type="desert" label="planet.type.desert">
			<body>starmap/planets/planet_desert_30x30</body>
			<equipment>colony/surfaces/desert/equipment_desert</equipment>
			<spacewar>colony/surfaces/desert/spacewar_desert</spacewar>
			<tileset pattern="colony/surfaces/desert/tile_desert_%03d">
				<tile-range start="21" end="54"/>
				<tile-range start="55" end="68" width="2" height="2"/>
				<tile id="69" height="2"/>
				<tile id="70" width="2" height="3"/>
				<tile-range start="71" end="74" width="3" height="3"/>
				<tile id="75" width="3" height="4"/>
				<tile-range start="76" end="79" width="4" height="4"/>
			</tileset>
			<map pattern="campaign/main/surfaces/desert_%d" start="1" end="9"/>
			<weather frequency='43200' duration='600' drop-type='RAIN'/>
		</planet>
		<planet type="earth" label="planet.type.earth">
			<body>starmap/planets/planet_earth_30x30</body>
			<equipment>colony/surfaces/earth/equipment_earth</equipment>
			<spacewar>colony/surfaces/earth/spacewar_earth</spacewar>
			<tileset pattern="colony/surfaces/earth/tile_earth_%03d">
				<tile-range start="21" end="107"/>
				<tile id="108" height="2"/>
				<tile-range start="109" end="130" width="2" height="2"/>
				<tile-range start="131" end="139" width="3" height="2"/>
				<tile-range start="140" end="147" width="2" height="3"/>
				<tile-range start="148" end="149" width="3" height="3"/>
				<tile-range start="150" end="158" width="4" height="4"/>
				<tile id="159" width="3" height="5"/>
				<tile id="160" width="5" height="6"/>
				<tile id="161" width="6" height="6"/>
			</tileset>
			<map pattern="campaign/main/surfaces/earth_%d" start="1" end="8"/>
			<weather frequency='4320' duration='120' drop-type='RAIN'/>
		</planet>
		<planet type="frozen" label="planet.type.frozen">
			<body>starmap/planets/planet_ice_30x30</body>
			<equipment>colony/surfaces/frozen/equipment_frozen</equipment>
			<spacewar>colony/surfaces/frozen/spacewar_frozen</spacewar>
			<tileset pattern="colony/surfaces/frozen/tile_frozen_%03d">
				<tile-range start="21" end="32"/>
				<tile-range start="33" end="37" width="2"/>
				<tile-range start="38" end="39" height="2"/>
				<tile-range start="40" end="54" width="2" height="2"/>
				<tile-range start="55" end="59" width="3" height="2"/>
				<tile-range start="60" end="62" width="4" height="2"/>
				<tile-range start="63" end="67" width="2" height="3"/>
				<tile id="68" width="3" height="3"/>
				<tile-range start="69" end="73" width="2" height="4"/>
				<tile-range start="74" end="78" width="4" height="4"/>
				<tile id="79" width="2" height="2"/>
			</tileset>
			<map pattern="campaign/main/surfaces/frozen_%d" start="1" end="9"/>
			<weather frequency='2880' duration='180' drop-type='SNOW'/>
		</planet>
		<planet type="liquid" label="planet.type.liquid">
			<body>starmap/planets/planet_liquid_30x30</body>
			<equipment>colony/surfaces/liquid/equipment_liquid</equipment>
			<spacewar>colony/surfaces/liquid/spacewar_liquid</spacewar>
			<tileset pattern="colony/surfaces/liquid/tile_liquid_%03d">
				<tile-range start="21" end="69"/>
				<tile-range start="70" end="72" width="2"/>
				<tile id="73" height="2"/>
				<tile-range start="74" end="79" width="2" height="2"/>
				<tile-range start="80" end="85"/>
				<tile-range start="86" end="103" width="2" height="2"/>
				<tile-range start="104" end="105" width="3" height="3"/>
				<tile id="106" width="3" height="2"/>
				<tile-range start="107" end="109" width="2" height="3"/>
				<tile-range start="110" end="116" width="3" height="3"/>
				<tile id="117" width="3" height="4"/>
				<tile id="118" width="3" height="3"/>
				<tile-range start="119" end="121" width="4" height="4"/>
				<tile-range start="122" end="123" width="3" height="3"/>
			</tileset>
			<map pattern="campaign/main/surfaces/liquid_%d" start="1" end="8"/>
			<weather frequency='1440' duration='120' drop-type='RAIN'/>
		</planet>
		<planet type="rocky" label="planet.type.rocky">
			<body>starmap/planets/planet_rocky_30x30</body>
			<equipment>colony/surfaces/rocky/equipment_rocky</equipment>
			<spacewar>colony/surfaces/rocky/spacewar_rocky</spacewar>
			<tileset pattern="colony/surfaces/rocky/tile_rocky_%03d">
				<tile-range start="21" end="41"/>
				<tile-range start="42" end="45" width="2"/>
				<tile-range start="46" end="58" width="2" height="2"/>
				<tile-range start="59" end="64" width="4" height="2"/>
				<tile-range start="65" end="71" width="3" height="3"/>
				<tile-range start="72" end="73" width="4" height="4"/>
				<tile id="74" width="5" height="5"/>
			</tileset>
			<map pattern="campaign/main/surfaces/rocky_%d" start="1" end="8"/>
			<weather frequency='5760' duration='120' drop-type='RAIN'/>
		</planet>
	</planets>
	<population-growths>
		<growth type="earth" race="human" value="2.0"/>
		<growth type="rocky" race="human" value="1.5"/>
		<growth type="cratered" race="human" value="1.25"/>
		<growth type="frozen" race="human" value="0.75"/>
		<growth type="liquid" race="human" value="0.75"/>
		<growth type="neptoplasm" race="human" value="0.5"/>
		<growth type="desert" race="human" value="0.5"/>
		<growth type="liquid" race="dargslan" value="2"/>
		<growth type="earth" race="dargslan" value="0.5"/>
		<growth type="frozen" race="garthog" value="2"/>
		<growth type="liquid" race="garthog" value="0.5"/>
		<growth type="desert" race="morgath" value="2"/>
		<growth type="liquid" race="sullep" value="1.25"/>
		<growth type="earth" race="sullep" value="0.75"/>
		<growth type="rocky" race="sullep" value="1.5"/>
		<growth type="desert" race="sullep" value="1.25"/>
		<growth type="neptoplasm" race="ecalep" value="2"/>
		<growth type="desert" race="ecalep" value="0.5"/>
		<growth type="frozen" race="ecalep" value="0.75"/>
		<growth type="rocky" race="ychom" value="2"/>
		<growth type="cratered" race="ychom" value="1.5"/>
		<growth type="rocky" race="dribs" value="2"/>
		<growth type="liquid" race="dribs" value="0.5"/>
	</population-growths>
	<planet-naming>
		<single label='planets.earth'>Earth</single>
		<single>Myridan</single>
		<single>Achilles</single>
		<single>Centronom</single>
		<single>Zeuson</single>
		<single>Naxos</single>
		<single>San Sterling</single>
		<single>Edgepolis</single>
		<single>Giantropolis</single>
		<single>New Caroline</single>
		
		<multiple>Center</multiple>
		<multiple>Outer</multiple>
		<multiple>Andromeda</multiple>
		<multiple>Exterior</multiple>
		<multiple>Garthog</multiple>
		<multiple>Magellan</multiple>
		<multiple>Persol</multiple>
	</planet-naming>
</galaxy>
