=== akarnokd/open-ig/data/generic/schemas/tech.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="tech">
		<xs:annotation>
			<xs:documentation>The list of technologies.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="item" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation><xs:documentation>A technology item's definition.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="item">
		<xs:annotation><xs:documentation>A technology item's definition.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="slot" type="slot">
					<xs:annotation><xs:documentation>A variable content equipment slot.</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="slot-fixed" type="slot-fixed">
					<xs:annotation><xs:documentation>A slot with fixed content.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:choice>
			<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The custom properties of the technology.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology unique identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label for the technology name, a sorter version displayed in width constrained listings.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="long-name" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label for the long name of the technology.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label for the description of the technology.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="category" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The category, see ResearchSubCategory enum.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="image" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The image reference used when displaying the 6 technology slots in equipment, research and production. This is a base image resource. Image with "_large" suffix will be displayed on the inventions screen. Image with "_wired_large" suffix will be displayed on the inventions screen when the technology is not yet researched. Image with "_tiny" suffix is used in the miniature images on the equipment screen. Image with "_small" suffix is used as the equipment customization image if present.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="factory" type="factory-enum" use="required">
			<xs:annotation><xs:documentation>The factory required to produce this technology.</xs:documentation></xs:annotation>
		</xs:attribute> 
		<xs:attribute name="research-cost" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The maximum research cost.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="production-cost" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The production cost.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="level" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The world level when the technology becomes available for research. Zero means instant availability.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="race" type="list-of-string" use="required">
			<xs:annotation><xs:documentation>The list of races who have this technology.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="civil" type="xs:positiveInteger" use="optional">
			<xs:annotation><xs:documentation>Number of required civil research centers.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="mech" type="xs:positiveInteger" use="optional">
			<xs:annotation><xs:documentation>Number of required mechanical research centers.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="comp" type="xs:positiveInteger" use="optional">
			<xs:annotation><xs:documentation>Number of required computer research centers.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="ai" type="xs:positiveInteger" use="optional">
			<xs:annotation><xs:documentation>Number of required A.I. research centers.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="mil" type="xs:positiveInteger" use="optional">
			<xs:annotation><xs:documentation>Number of required military research centers.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="index" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The slot index when the technology is listed on equipment, research and production screens.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="video" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The video animation for this technology. If not present, one of the static images will be used.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="requires" type="list-of-string" use="optional">
			<xs:annotation><xs:documentation>The optional list of required technologies to be available before this technology can be researched.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="nobuild" type="xs:boolean" use="optional">
			<xs:annotation><xs:documentation>Do not let the player build this technology. It can only be awarded by scripting.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="skirmish-race" type="list-of-string" use="optional">
			<xs:annotation><xs:documentation>The list of races who have this technology in skirmish.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="slot">
		<xs:annotation><xs:documentation>A variable content equipment slot.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The slot's identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="x" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The X coordinate of the equipment rectangle.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="y" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The Y coordinate of the equipment rectangle.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="width" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The width of the equipment rectangle.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="height" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The height of the equipment rectangle.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="max" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The maximum amount of items.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="items" type="list-of-string" use="required">
			<xs:annotation><xs:documentation>The list of technologies that could be equipped in the slot.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="slot-fixed">
		<xs:annotation><xs:documentation>A slot with fixed content.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The slot's identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="count" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The number of items in the slot.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="item" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology identifier filling the slot.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="factory-enum">
		<xs:annotation><xs:documentation>The factory type enumeration.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="spaceship"/>
			<xs:enumeration value="weapon"/>
			<xs:enumeration value="equipment"/>
			<xs:enumeration value="building"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="list-of-string">
		<xs:annotation><xs:documentation>A list of string.</xs:documentation></xs:annotation>
		<xs:list itemType="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="property">
		<xs:annotation><xs:documentation>A custom property definition.</xs:documentation></xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The property name.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The property value.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/open-ig/data/generic/campaign/main/tech.xml
<?xml version="1.0" encoding="UTF-8"?>
<tech xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/tech.xsd">
	<item id="Fighter1" name="tech.fighter1.name" long-name="tech.fighter1.longname" description="tech.fighter1.description" category="SPACESHIPS_FIGHTERS" image="inventions/spaceships/fighters/fighter_1" factory="spaceship" research-cost="3000" production-cost="2000" level="0" race="human" ai="1" mil="1" index="0" video="technology/spaceships/fighters/fighter_1">
		<slot-fixed id="Laser" count="1" item="Laser1"/>
	</item>
	<item id="Fighter2" name="tech.fighter2.name" long-name="tech.fighter2.longname" description="tech.fighter2.description" category="SPACESHIPS_FIGHTERS" image="inventions/spaceships/fighters/fighter_2" factory="spaceship" research-cost="4000" production-cost="3200" level="2" race="human" mech="1" ai="1" mil="1" index="1" video="technology/spaceships/fighters/fighter_2">
		<slot-fixed id="Laser" count="2" item="Laser1"/>
	</item>
	<item id="Fighter3" name="tech.fighter3.name" long-name="tech.fighter3.longname" description="tech.fighter3.description" category="SPACESHIPS_FIGHTERS" image="inventions/spaceships/fighters/fighter_3" factory="spaceship" research-cost="12000" production-cost="5000" level="3" race="human" mech="1" comp="2" ai="2" mil="2" index="2" video="technology/spaceships/fighters/fighter_3">
		<slot-fixed id="Laser" count="2" item="Laser2"/>
	</item>
	<item id="Fighter4" name="tech.fighter4.name" long-name="tech.fighter4.longname" description="tech.fighter4.description" category="SPACESHIPS_FIGHTERS" image="inventions/spaceships/fighters/fighter_4" factory="spaceship" research-cost="18000" production-cost="7500" level="4" race="human" requires="Fighter3" mech="3" comp="2" ai="2" mil="4" index="3" video="technology/spaceships/fighters/fighter_4">
		<slot-fixed id="Laser" count="2" item="Laser2"/>
	</item>
	<item id="Fighter5" name="tech.fighter5.name" long-name="tech.fighter5.longname" description="tech.fighter5.description" category="SPACESHIPS_FIGHTERS" image="inventions/spaceships/fighters/fighter_5" factory="spaceship" research-cost="22000" production-cost="10000" level="4" race="human" civil="1" mech="5" comp="4" ai="4" mil="5" index="4" video="technology/spaceships/fighters/fighter_5" requires="Fighter4">
		<slot-fixed id="Laser" count="2" item="Laser3"/>
	</item>
	<item id="Fighter6" name="tech.fighter6.name" long-name="tech.fighter6.longname" description="tech.fighter6.description" category="SPACESHIPS_FIGHTERS" image="inventions/spaceships/fighters/fighter_6" factory="spaceship" research-cost="24000" production-cost="12000" level="5" race="human" requires="Rocket2,Fighter5" mech="4" comp="4" ai="5" mil="7" index="5" video="technology/spaceships/fighters/fighter_6">
		<slot-fixed id="Laser" count="2" item="Laser3"/>
	</item>
	<item id="Destroyer1" name="tech.destroyer1.name" long-name="tech.destroyer1.longname" description="tech.destroyer1.description" category="SPACESHIPS_CRUISERS" image="inventions/spaceships/cruisers/destroyer_1" factory="spaceship" research-cost="10000" production-cost="12000" level="0" race="human" comp="1" ai="1" mil="1" index="0" video="technology/spaceships/cruisers/destroyer_1">
		<slot id="shield" x="109" y="58" width="26" height="12" max="1" items="Shield1, Shield2"/>
		<slot id="laser" x="163" y="46" width="16" height="15" max="6" items="Laser1, Laser2, Laser3"/>
		<slot id="hyperdrive" x="203" y="56" width="24" height="11" max="1" items="HyperDrive1, HyperDrive2"/>
	</item>
	<item id="Destroyer2" name="tech.destroyer2.name" long-name="tech.destroyer2.longname" description="tech.destroyer2.description" category="SPACESHIPS_CRUISERS" image="inventions/spaceships/cruisers/destroyer_2" factory="spaceship" research-cost="32000" production-cost="17500" level="3" race="human" requires="Laser2" mech="2" comp="1" ai="1" mil="2" index="1" video="technology/spaceships/cruisers/destroyer_2">
		<slot id="laser1" x="187" y="39" width="24" height="15" max="8" items="Laser1, Laser2, Laser3"/>
		<slot id="shield" x="149" y="61" width="21" height="12" max="1" items="Shield1, Shield2"/>
		<slot id="laser2" x="185" y="66" width="24" height="15" max="6" items="Laser1, Laser2, Laser3"/>
		<slot id="hyperdrive" x="218" y="57" width="28" height="18" max="1" items="HyperDrive1, HyperDrive2, HyperDrive3"/>
	</item>
	<item id="Destroyer3" name="tech.destroyer3.name" long-name="tech.destroyer3.longname" description="tech.destroyer3.description" category="SPACESHIPS_CRUISERS" image="inventions/spaceships/cruisers/destroyer_3" factory="spaceship" research-cost="44000" production-cost="22000" level="4" race="human" requires="Radar2, HyperDrive4, PlasmaCannon" mech="3" comp="4" ai="3" mil="4" index="2" video="technology/spaceships/cruisers/destroyer_3">
		<slot id="radar" x="55" y="38" width="28" height="17" max="1" items="Radar1, Radar2"/>
		<slot id="shield" x="87" y="47" width="30" height="11" max="1" items="Shield1, Shield2"/>
		<slot id="laser1" x="181" y="14" width="21" height="10" max="9" items="Laser1, Laser2, Laser3"/>
		<slot id="hyperdrive" x="207" y="58" width="27" height="22" max="1" items="HyperDrive1, HyperDrive2, HyperDrive3, HyperDrive4, HyperDrive5"/>
		<slot id="laser2" x="169" y="84" width="22" height="10" max="9" items="Laser1, Laser2, Laser3"/>
		<slot id="cannon" x="184" y="102" width="16" height="15" max="4" items="IonCannon, PlasmaCannon, ParticleCannon"/>
	</item>
	<item id="Cruiser1" name="tech.cruiser1.name" long-name="tech.cruiser1.longname" description="tech.cruiser1.description" category="SPACESHIPS_CRUISERS" image="inventions/spaceships/cruisers/cruiser_1" factory="spaceship" research-cost="24000" production-cost="15000" level="2" race="human" requires="Shield1" mech="1" comp="1" ai="1" mil="1" index="3" video="technology/spaceships/cruisers/cruiser_1">
		<slot id="shield" x="60" y="62" width="36" height="13" max="1" items="Shield1, Shield2, Shield3, Shield4"/>
		<slot id="laser" x="128" y="67" width="23" height="14" max="8" items="Laser1, Laser2, Laser3, Laser4"/>
		<slot id="cannon" x="150" y="42" width="33" height="17" max="2" items="IonCannon, PlasmaCannon, ParticleCannon"/>
		<slot id="radar" x="192" y="38" width="30" height="17" max="1" items="Radar1, Radar2"/>
		<slot id="hyperdrive" x="206" y="63" width="30" height="22" max="1" items="HyperDrive1, HyperDrive2, HyperDrive3, HyperDrive4"/>
	</item>
	<item id="Cruiser2" name="tech.cruiser2.name" long-name="tech.cruiser2.longname" description="tech.cruiser2.description" category="SPACESHIPS_CRUISERS" image="inventions/spaceships/cruisers/cruiser_2" factory="spaceship" research-cost="50000" production-cost="25000" level="4" race="human" requires="Shield2, Laser2, Radar2" mech="2" comp="3" ai="3" mil="4" index="4" video="technology/spaceships/cruisers/cruiser_2">
		<slot id="shield" x="57" y="71" width="40" height="19" max="1" items="Shield1, Shield2, Shield3, Shield4"/>
		<slot id="radar" x="123" y="75" width="28" height="12" max="1" items="Radar1, Radar2"/>
		<slot id="laser" x="161" y="65" width="26" height="17" max="13" items="Laser1, Laser2, Laser3, Laser4"/>
		<slot id="cannon1" x="168" y="45" width="40" height="13" max="3" items="IonCannon, PlasmaCannon"/>
		<slot id="cannon2" x="183" y="85" width="38" height="13" max="5" items="IonCannon"/>
		<slot id="hyperdrive" x="216" y="59" width="29" height="19" max="1" items="HyperDrive1, HyperDrive2, HyperDrive3, HyperDrive4, HyperDrive5"/>
	</item>
	<item id="Cruiser3" name="tech.cruiser3.name" long-name="tech.cruiser3.longname" description="tech.cruiser3.description" category="SPACESHIPS_CRUISERS" image="inventions/spaceships/cruisers/cruiser_3" factory="spaceship" research-cost="70000" production-cost="36000" level="5" race="human" requires="HyperDrive5,Shield2,Bomb2" civil="1" mech="4" comp="5" ai="4" mil="7" index="5" video="technology/spaceships/cruisers/cruiser_3">
		<slot id="laser" x="38" y="67" width="21" height="10" max="16" items="Laser1, Laser2, Laser3, Laser4"/>
		<slot id="shield" x="63" y="62" width="24" height="12" max="1" items="Shield2, Shield3, Shield4"/>
		<slot id="bomb" x="133" y="45" width="22" height="22" max="4" items="Bomb1, Bomb2"/>
		<slot id="rocket" x="153" y="72" width="25" height="14" max="4" items="Rocket1, Rocket2, MultiheadedRocket"/>
		<slot id="cannon1" x="180" y="58" width="17" height="14" max="10" items="PlasmaCannon, ParticleCannon, MesonCannon"/>
		<slot id="ecm" x="199" y="71" width="22" height="11" max="1" items="ECM1, ECM2"/>
		<slot id="cannon2" x="207" y="56" width="15" height="14" max="10" items="PlasmaCannon, ParticleCannon, MesonCannon"/>
		<slot id="hyperdrive" x="235" y="55" width="23" height="21" max="1" items="HyperDrive1, HyperDrive2, HyperDrive3, HyperDrive4, HyperDrive5"/>
	</item>
	<item id="Battleship1" name="tech.battleship1.name" long-name="tech.battleship1.longname" description="tech.battleship1.description" category="SPACESHIPS_BATTLESHIPS" image="inventions/spaceships/battleships/battleship_1" factory="spaceship" research-cost="100000" production-cost="80000" level="3" race="human" requires="OrbitalFactory" civil="1" mech="1" comp="1" ai="1" mil="1" index="0" video="technology/spaceships/battleships/battleship_1">
		<slot id="laser" x="45" y="53" width="21" height="10" max="14" items="Laser1, Laser2, Laser3, Laser4"/>
		<slot id="bomb" x="80" y="64" width="22" height="13" max="8" items="Bomb1, Bomb2"/>
		<slot id="rocket" x="115" y="65" width="23" height="17" max="6" items="Rocket1, Rocket2, MultiheadedRocket"/>
		<slot id="radar" x="140" y="17" width="15" height="11" max="1" items="Radar1, Radar2, Radar3"/>
		<slot id="cannon" x="143" y="57" width="15" height="13" max="8" items="IonCannon, PlasmaCannon"/>
		<slot id="storage" x="161" y="61" width="21" height="15" max="1" items="Storage1, Storage2"/>
