=== akarnokd/open-ig/trunk/open-ig/data/generic/schemas/buildings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="buildings" type="buildings">
		<xs:annotation>
			<xs:documentation>The list of buildings available in the game.
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="buildings">
		<xs:annotation>
			<xs:documentation>The list of buildings.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="building" type="building" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The definition of a single building.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="roads" type="roads">
				<xs:annotation>
					<xs:documentation>The road tiles for each race and configuration.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="scaffolding" type="scaffolding">
				<xs:annotation>
					<xs:documentation>The scaffolding used when a building is
						constructed for each race.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="building">
		<xs:annotation>
			<xs:documentation>The definition of a building.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="graphics" type="graphics">
				<xs:annotation>
					<xs:documentation>The graphical form of the building.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="build" type="build">
				<xs:annotation>
					<xs:documentation>The construction related properties.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="operation" type="operation">
				<xs:annotation>
					<xs:documentation>The operational resource lists.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="upgrades" type="upgrades">
				<xs:annotation>
					<xs:documentation>The list of available upgrades to this building.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The unique identifier of the building.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The label for the building name. The value +
					".desc" is used as the short description.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="graphics">
		<xs:annotation>
			<xs:documentation>The graphics for each race of a building.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="tech" type="graphics-type" minOccurs="1"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The race-specific building dimensions.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="graphics-type">
		<xs:annotation>
			<xs:documentation>The race-specific building dimensions.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The race identifier.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="width" type="xs:positiveInteger" use="required">
			<xs:annotation>
				<xs:documentation>The building width in cells. Width points
					bottom-left to top-right direction.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="height" type="xs:positiveInteger"
			use="required">
			<xs:annotation>
				<xs:documentation>The building height in cells. Height points
					top-left to bottom-right.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="image" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The image resource base name. Additional images are "_damaged", "_mini" and "_lights".</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="skirmish-only" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>The race-specific building should only be present in skirmish games.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="build">
		<xs:annotation>
			<xs:documentation>The construction properties</xs:documentation>
		</xs:annotation>
		<xs:attribute name="cost" type="xs:nonNegativeInteger"
			use="required">
			<xs:annotation>
				<xs:documentation>The construction cost.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="kind" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Used to establish the same-kind of buildings, such
					as laboratories.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="limit" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The limit of the building. Star (*) means
					unlimited, a positive number means an exact limit, a negative
					number means a kind-limit.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="except" type="string-list" use="optional">
			<xs:annotation>
				<xs:documentation>The list of planet surface types where the
					building can't be built.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="research" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The research prerequisite of the building.
					References a technology in tech.xml .</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="string-list">
		<xs:annotation>
			<xs:documentation>A comma separated list of strings.
			</xs:documentation>
		</xs:annotation>
		<xs:list itemType="xs:string" />
	</xs:simpleType>
	<xs:complexType name="operation">
		<xs:annotation>
			<xs:documentation>The operational requirements of a building.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="resource" type="resource" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The resource definition.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="percent" type="xs:boolean" use="optional">
			<xs:annotation>
				<xs:documentation>Should the operational resources be scaled
					according to the building efficiency?</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="resource">
		<xs:annotation>
			<xs:documentation>The resource definition. Generally, negative values
				represent consumption.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="type" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>The resource type.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="display" type="xs:boolean" use="optional">
					<xs:annotation>
						<xs:documentation>Display this resource as the primary output of
							the building on the information panels?</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="upgrades">
		<xs:annotation>
			<xs:documentation>The available upgrades of this building.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="upgrade" type="upgrade" minOccurs="0"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The upgrade resource settings. The position
						represents the upgrade level.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="upgrade">
		<xs:annotation>
			<xs:documentation>The definition of an upgrade level. The position
				represents the upgrade level.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="resource" type="upgrade-resource"
				minOccurs="1" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The upgrade resource multiplier. The level
						multipliers do not stack.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="desc" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The upgrade description to display.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="upgrade-resource">
		<xs:annotation>
			<xs:documentation>The resource definition. Generally, negative values
				represent consumption.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="type" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>The resource type.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="roads">
		<xs:annotation>
			<xs:documentation>The definition of road tiles for various races.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="graphics" type="road-graphics">
				<xs:annotation>
					<xs:documentation>The resource location of road graphics.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="layout" type="layout" minOccurs="1"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The layout definition of the road.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="road-graphics">
		<xs:annotation>
			<xs:documentation>The resource location of road graphics.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="tech" type="road-tech" minOccurs="1"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The race names.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="base" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Contains the resource pattern for the road tiles,
					first parameter is the race, the second parameter is the layout id.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="road-tech">
		<xs:annotation>
			<xs:documentation>The road race identifier.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The race identifier.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="layout">
		<xs:annotation>
			<xs:documentation>The layout definition of the road cell.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The resource name of the road image.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="enum" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The enumeration representing the road connections.
					See hu.openig.core.RoadType enumeration.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="index" type="xs:positiveInteger" use="required">
			<xs:annotation>
				<xs:documentation>The logical index of the given road tile.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="scaffolding">
		<xs:annotation>
			<xs:documentation>The definition of scaffolding graphics.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="graphics" type="scaffolding-graphics">
				<xs:annotation>
					<xs:documentation>The scaffolding graphics list for each race.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="scaffolding-graphics">
		<xs:annotation>
			<xs:documentation>The scaffolding graphics list for each race.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="tech" type="scaffolding-tech" minOccurs="1"
				maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The scaffolding for a specific race.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="base" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The base resource path to the scaffolding images.
					The first parameter is the race id, the second parameter is the
					scaffolding image name calculated from the normal.base and
					damaged.base subelements.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="scaffolding-tech">
		<xs:annotation>
			<xs:documentation>The race specific scaffolding images.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="normal" type="scaffolding-item">
				<xs:annotation>
					<xs:documentation>The scaffolding images for the normal look.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="damaged" type="scaffolding-item">
				<xs:annotation>
					<xs:documentation>The scaffolding images for the damaged look.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The race identifier.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="scaffolding-item">
		<xs:annotation>
			<xs:documentation>The scaffolding item defining mutliple images with
				a pattern.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="base" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The base pattern for the image resource having a
					single parameter for indexing the individual images.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="from" type="xs:integer" use="required">
			<xs:annotation>
				<xs:documentation>The starting index for the scaffolding image
					pattern, inclusive.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="to" type="xs:integer" use="required">
			<xs:annotation>
				<xs:documentation>The end index for the scaffolding image pattern,
					inclusive.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/data/generic/campaign/main/buildings.xml
<?xml version='1.0' encoding='UTF-8'?>
<buildings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='../../schemas/buildings.xsd'>
  <building id='ColonyHub' name='buildings.colony_hub'>
    <graphics>
      <tech id='human' width='8' height='7' image='colony/buildings/human/colony_hub'/>
      <tech id='garthog' height='6' width='3' image='colony/buildings/garthog/colony_hub'/>
      <tech id='morgath' height='5' width='6' image='colony/buildings/morgath/colony_hub'/>
      <tech id='ychom' height='3' width='3' image='colony/buildings/ychom/colony_hub'/>
      <tech id='dribs' height='4' width='4' image='colony/buildings/dribs/colony_hub'/>
      <tech id='sullep' height='3' width='4' image='colony/buildings/sullep/colony_hub'/>
      <tech id='dargslan' height='8' width='5' image='colony/buildings/dargslan/colony_hub'/>
      <tech id='ecalep' height='4' width='4' image='colony/buildings/ecalep/colony_hub'/>
    </graphics>
    <build cost='40000' kind='MainBuilding' limit='1'/>
    <operation>
      <resource type='energy'>0</resource>
      <resource type='worker'>-960</resource>
      <resource type='food'>5000</resource>
      <resource type='police'>7500</resource>
      <resource type='hospital'>10000</resource>
      <resource type='house'>5000</resource>
    </operation>
    <upgrades/>
  </building>
  <building id='PrefabHousing' name='buildings.prefab_housing'>
    <graphics>
      <tech id='human' width='4' height='3' image='colony/buildings/human/prefab_housing'/>
      <tech id='garthog' width='2' height='2' image='colony/buildings/garthog/prefab_housing' skirmish-only='true'/>
      <tech id='morgath' width='2' height='2' image='colony/buildings/morgath/prefab_housing' skirmish-only='true'/>
      <tech id='ecalep' width='2' height='2' image='colony/buildings/ecalep/prefab_housing' skirmish-only='true'/>
      <tech id='sullep' width='2' height='1' image='colony/buildings/sullep/prefab_housing' skirmish-only='true'/>
      <tech id='ychom' width='2' height='2' image='colony/buildings/ychom/prefab_housing' skirmish-only='true'/>
      <tech id='dribs' width='2' height='1' image='colony/buildings/dribs/prefab_housing' skirmish-only='true'/>
      <tech id='dargslan' width='2' height='2' image='colony/buildings/dargslan/prefab_housing' skirmish-only='true'/>
    </graphics>
    <build cost='5600' kind='House' limit='*'/>
    <operation>
      <resource type='energy'>-850</resource>
      <resource type='worker'>-60</resource>
      <resource type='house' display='true'>7000</resource>
    </operation>
    <upgrades>
      <upgrade desc='buildings.housing.upgrade_1'>
        <resource type='house'>1.25</resource>
        <resource type='energy'>1.25</resource>
        <resource type='worker'>1.25</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_2'>
        <resource type='house'>1.5</resource>
        <resource type='energy'>1.5</resource>
        <resource type='worker'>1.5</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_3'>
        <resource type='house'>2</resource>
        <resource type='energy'>2</resource>
        <resource type='worker'>1.75</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_4'>
        <resource type='house'>2.5</resource>
        <resource type='energy'>2</resource>
        <resource type='worker'>1.75</resource>
      </upgrade>
    </upgrades>
  </building>
  <building id='ApartmentBlock' name='buildings.apartment_block'>
    <graphics>
      <tech id='human' width='4' height='3' image='colony/buildings/human/apartment_block'/>
      <tech id='garthog' width='2' height='2' image='colony/buildings/garthog/apartment_block' skirmish-only='true'/>
      <tech id='morgath' width='2' height='3' image='colony/buildings/morgath/apartment_block' skirmish-only='true'/>
      <tech id='ecalep' width='2' height='2' image='colony/buildings/ecalep/apartment_block' skirmish-only='true'/>
      <tech id='sullep' width='2' height='2' image='colony/buildings/sullep/apartment_block' skirmish-only='true'/>
      <tech id='ychom' width='3' height='2' image='colony/buildings/ychom/apartment_block' skirmish-only='true'/>
      <tech id='dribs' width='2' height='2' image='colony/buildings/dribs/apartment_block' skirmish-only='true'/>
      <tech id='dargslan' width='2' height='3' image='colony/buildings/dargslan/apartment_block' skirmish-only='true'/>
    </graphics>
    <build cost='12000' kind='House' limit='*'/>
    <operation>
      <resource type='house' display='true'>15000</resource>
      <resource type='energy'>-1200</resource>
      <resource type='worker'>-70</resource>
    </operation>
    <upgrades>
      <upgrade desc='buildings.housing.upgrade_1'>
        <resource type='house'>1.25</resource>
        <resource type='energy'>1.25</resource>
        <resource type='worker'>1.25</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_2'>
        <resource type='house'>1.5</resource>
        <resource type='energy'>1.5</resource>
        <resource type='worker'>1.5</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_3'>
        <resource type='house'>2</resource>
        <resource type='energy'>2</resource>
        <resource type='worker'>1.75</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_4'>
        <resource type='house'>2.5</resource>
        <resource type='energy'>2</resource>
        <resource type='worker'>1.75</resource>
      </upgrade>
    </upgrades>
  </building>
  <building name='buildings.arcology' id='Arcology'>
    <graphics>
      <tech id='human' height='4' width='3' image='colony/buildings/human/arcology'/>
      <tech id='garthog' height='2' width='3' image='colony/buildings/garthog/arcology'/>
      <tech id='morgath' height='4' width='2' image='colony/buildings/morgath/arcology'/>
      <tech id='ychom' height='3' width='3' image='colony/buildings/ychom/arcology'/>
      <tech id='dribs' height='3' width='2' image='colony/buildings/dribs/arcology'/>
      <tech id='sullep' height='2' width='2' image='colony/buildings/sullep/arcology'/>
      <tech id='dargslan' height='2' width='3' image='colony/buildings/dargslan/arcology'/>
      <tech id='ecalep' height='3' width='2' image='colony/buildings/ecalep/arcology'/>
    </graphics>
    <build limit='*' kind='House' cost='16000'/>
    <operation>
      <resource type='house' display='true'>30000</resource>
      <resource type='energy'>-1500</resource>
      <resource type='worker'>-100</resource>
    </operation>
    <upgrades>
      <upgrade desc='buildings.housing.upgrade_1'>
        <resource type='house'>1.25</resource>
        <resource type='energy'>1.25</resource>
        <resource type='worker'>1.25</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_2'>
        <resource type='house'>1.5</resource>
        <resource type='energy'>1.5</resource>
        <resource type='worker'>1.5</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_3'>
        <resource type='house'>2</resource>
        <resource type='energy'>2</resource>
        <resource type='worker'>1.75</resource>
      </upgrade>
      <upgrade desc='buildings.housing.upgrade_4'>
        <resource type='house'>2.5</resource>
        <resource type='energy'>2</resource>
        <resource type='worker'>1.75</resource>
      </upgrade>
    </upgrades>
  </building>
  <building name='buildings.nuclear_plant' id='NuclearPlant'>
    <graphics>
      <tech height='5' width='5' id='human' image='colony/buildings/human/nuclear_plant'/>
      <tech id='garthog' height='3' width='3' image='colony/buildings/garthog/nuclear_plant'/>
      <tech id='morgath' height='3' width='3' image='colony/buildings/morgath/nuclear_plant'/>
      <tech id='ychom' height='4' width='4' image='colony/buildings/ychom/nuclear_plant'/>
      <tech id='dribs' height='5' width='4' image='colony/buildings/dribs/nuclear_plant'/>
      <tech id='sullep' height='4' width='4' image='colony/buildings/sullep/nuclear_plant'/>
      <tech id='dargslan' height='5' width='4' image='colony/buildings/dargslan/nuclear_plant'/>
      <tech id='ecalep' height='3' width='4' image='colony/buildings/ecalep/nuclear_plant'/>
    </graphics>
    <build limit='*' kind='Power' cost='8000'/>
    <operation percent='true'>
      <resource type='energy' display='true'>3500</resource>
      <resource type='worker'>-290</resource>
    </operation>
    <upgrades>
      <upgrade desc='buildings.power.upgrade_1'>
        <resource type='energy'>1.5</resource>
        <resource type='worker'>1.25</resource>
      </upgrade>
      <upgrade desc='buildings.power.upgrade_2'>
        <resource type='energy'>2</resource>
        <resource type='worker'>1.5</resource>
      </upgrade>
      <upgrade desc='buildings.power.upgrade_3'>
        <resource type='energy'>2.5</resource>
        <resource type='worker'>2</resource>
      </upgrade>
      <upgrade desc='buildings.power.upgrade_4'>
        <resource type='energy'>3</resource>
        <resource type='worker'>2</resource>
      </upgrade>
    </upgrades>
  </building>
  <building name='buildings.fusion_plant' id='FusionPlant'>
    <graphics>
      <tech height='5' width='5' id='human' image='colony/buildings/human/fusion_plant'/>
      <tech height='5' width='3' id='garthog' image='colony/buildings/garthog/fusion_plant' skirmish-only="true"/>
      <tech height='4' width='4' id='morgath' image='colony/buildings/morgath/fusion_plant' skirmish-only="true"/>
      <tech height='4' width='4' id='ecalep' image='colony/buildings/ecalep/fusion_plant' skirmish-only="true"/>
