=== akarnokd/open-ig/trunk/open-ig/data/generic/schemas/definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="definition" type="definition">
		<xs:annotation>
			<xs:documentation>The definition of a campaign.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="definition">
		<xs:annotation><xs:documentation>The definition of a campaign.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="texts" type="texts" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The textual description of the campaign in a language.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="image" type="xs:string">
				<xs:annotation><xs:documentation>The image resource to display on the single player screen when the campaign is selected. Leave empty for no image.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="intro" type="xs:string">
				<xs:annotation><xs:documentation>The intro video resource to play when the campaign is started. Leave empty for no intro video.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="level" type="xs:positiveInteger">
				<xs:annotation><xs:documentation>The initial level of the campaign.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="battle" type="xs:string">
				<xs:annotation><xs:documentation>The battle.xml resource location describing the space and ground battles.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="bridge" type="xs:string">
				<xs:annotation><xs:documentation>The bride.xml resource location describing the bridge.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="buildings" type="xs:string">
				<xs:annotation><xs:documentation>The buildings.xml resource location describing the buildings.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="diplomacy" type="xs:string">
				<xs:annotation><xs:documentation>The diplomacy.xml resource location describing the diplomatic options.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="galaxy" type="xs:string">
				<xs:annotation><xs:documentation>The galaxy.xml resource location describing the galaxy and planet types.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="planets" type="xs:string">
				<xs:annotation><xs:documentation>The planets.xml resource location describing the planets and their initial conditions.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="players" type="xs:string">
				<xs:annotation><xs:documentation>The players.xml resource location describing the players of the game.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="talks" type="xs:string">
				<xs:annotation><xs:documentation>The talks.xml resource location describing the available bar talks used by the original game.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="tech" type="xs:string">
				<xs:annotation><xs:documentation>The tech.xml resource location describing the researchable and producable technologies.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="test" type="xs:string">
				<xs:annotation><xs:documentation>The test.xml resource location describing a test used by the original game.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="walks" type="xs:string">
				<xs:annotation><xs:documentation>The walks.xml resource location describing the ship walking positions and videos.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="scripting" type="xs:string">
				<xs:annotation><xs:documentation>The scripting.xml resource location used to script missions in the campaign.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="chats" type="xs:string">
				<xs:annotation><xs:documentation>The chat.xml resource location describing the space-chat during battles.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="texts">
		<xs:annotation><xs:documentation>The textual description of the campaign in a specific language.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="title" type="xs:string">
				<xs:annotation><xs:documentation>The short title to display in the campaign list.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="description" type="xs:string">
				<xs:annotation><xs:documentation>The description of the campaign.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="language" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The two character language.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/open-ig/data/generic/skirmish/human/definition.xml
<?xml version='1.0' encoding='UTF-8'?>
<definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/definition.xsd">
	<texts language='hu'>
		<title>Ember vs. MI</title>
		<description>Küzdelem a gép ellen. Három bolygóról indulva kell legyőzni az ellenfelet.</description>
	</texts>
	<texts language='en'>
		<title>Human vs. AI</title>
		<description>Fight against the machine. Starting with three planets you should defeat the adversary.</description>
	</texts>
	<texts language='fr'>
		<title>Human vs. AI</title>
		<description>Fight against the machine. Starting with three planets you should defeat the adversary.</description>
	</texts>
	<texts language='de'>
		<title>Human vs. AI</title>
		<description>Fight against the machine. Starting with three planets you should defeat the adversary.</description>
	</texts>
	<texts language='ru'>
		<title>Human vs. AI</title>
		<description>Fight against the machine. Starting with three planets you should defeat the adversary.</description>
	</texts>
	<image></image>
	<intro></intro>
	<level>5</level>
	<battle>campaign/main/battle</battle>
	<bridge>campaign/main/bridge</bridge>
	<buildings>campaign/main/buildings</buildings>
	<diplomacy>campaign/main/diplomacy</diplomacy>
	<galaxy>campaign/main/galaxy</galaxy>
	<planets>skirmish/human/planets</planets>
	<players>skirmish/human/players</players>
	<talks>campaign/main/talks</talks>
	<tech>skirmish/human/tech</tech>
	<test>campaign/main/test</test>
	<walks>campaign/main/walks</walks>
	<scripting>skirmish/human/scripting</scripting>
	<chats>campaign/main/chat</chats>
	<spies>campaing/main/spies</spies>
	<parameters		
	    groundRadarUnitSize="35" 
		fleetRadarUnitSize="25" 
		researchSpeed="8" 
		productionUnit="0.004" 
		constructionSpeed="20" 
		constructionCost="20" 
		repairSpeed="10" 
		repairCost="2" 
		costToHitpoints="10" 
		nearbyDistance="10" 
		simulationRatio="10" 
		fleetSpeed="0.0064" 
		stationLimit="3" 
		battleshipLimit="3" 
		fighterLimit="30" 
		mediumshipLimit="25"
		radarShareLimit="80"
		blackMarketRestockTime="4320"
/>
</definition>

=== akarnokd/open-ig/trunk/open-ig/dlc/gump891202-racemod-0.1/generic/skirmish/racemod-0.1/definition.xml
<?xml version='1.0' encoding='UTF-8'?>
<definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/definition.xsd">
	<texts language='hu'>
		<title>Gummp891202 Race Mod</title>
		<description>Gummp891202 Race Mod, felturbózott idegen technológiákkal, kifejezetten egyéni játékra.</description>
	</texts>
	<texts language='en'>
		<title>Gummp891202 Race Mod</title>
		<description>Gummp891202 Race Mod with improved alien technologies, for skirmish play.</description>
	</texts>
	<image></image>
	<intro></intro>
	<level>5</level>
	<battle>skirmish/racemod-0.1/battle</battle>
	<bridge>campaign/main/bridge</bridge>
	<buildings>skirmish/racemod-0.1/buildings</buildings>
	<diplomacy>campaign/main/diplomacy</diplomacy>
	<galaxy>campaign/main/galaxy</galaxy>
	<planets>skirmish/racemod-0.1/planets</planets>
	<players>skirmish/racemod-0.1/players</players>
	<talks>campaign/main/talks</talks>
	<tech>skirmish/racemod-0.1/tech</tech>
	<test>campaign/main/test</test>
	<walks>campaign/main/walks</walks>
	<scripting>skirmish/racemod-0.1/scripting</scripting>
	<chats>campaign/main/chat</chats>
</definition>

=== akarnokd/open-ig/trunk/open-ig-0.95/data/generic/campaign/main2/definition.xml
<?xml version='1.0' encoding='UTF-8'?>
<definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/definition.xsd">
	<texts language='hu'>
		<title>Főkampány (szabad)</title>
		<description>Az eredeti Imperium Galactica főkampánya. Szabad játékmenet.</description>
	</texts>
	<texts language='en'>
		<title>Main Campaign (free)</title>
		<description>The main campaign of the original Imperium Galactica. Free gameplay.</description>
	</texts>
	<image>campaign/main/main_campaign_image</image>
	<intro>interlude/campaign_start</intro>
	<level>5</level>
	<battle>campaign/main/battle</battle>
	<bridge>campaign/main/bridge</bridge>
	<buildings>campaign/main/buildings</buildings>
	<diplomacy>campaign/main/diplomacy</diplomacy>
	<galaxy>campaign/main/galaxy</galaxy>
	<planets>campaign/main/planets</planets>
	<players>campaign/main/players</players>
	<talks>campaign/main/talks</talks>
	<tech>campaign/main/tech</tech>
	<test>campaign/main/test</test>
	<walks>campaign/main/walks</walks>
	<scripting>skirmish/human/scripting</scripting>
	<chats>campaign/main/chat</chats>
</definition>

=== akarnokd/open-ig/data/generic/campaign/main2/definition.xml
<?xml version='1.0' encoding='UTF-8'?>
<definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/definition.xsd">
	<texts language='hu'>
		<title>Főkampány (szabad)</title>
		<description>Az eredeti Imperium Galactica főkampánya. Szabad játékmenet.</description>
	</texts>
	<texts language='en'>
		<title>Main Campaign (free)</title>
		<description>The main campaign of the original Imperium Galactica. Free gameplay.</description>
	</texts>
	<texts language='fr'>
		<title>Main Campaign (free)</title>
		<description>The main campaign of the original Imperium Galactica. Free gameplay.</description>
	</texts>
	<texts language='de'>
		<title>Main Campaign (free)</title>
		<description>The main campaign of the original Imperium Galactica. Free gameplay.</description>
	</texts>
	<texts language='ru'>
		<title>Main Campaign (free)</title>
		<description>The main campaign of the original Imperium Galactica. Free gameplay.</description>
	</texts>
	<image>campaign/main/main_campaign_image</image>
	<intro>interlude/campaign_start</intro>
	<level>5</level>
	<battle>campaign/main/battle</battle>
	<bridge>campaign/main/bridge</bridge>
	<buildings>campaign/main/buildings</buildings>
	<diplomacy>campaign/main/diplomacy</diplomacy>
	<galaxy>campaign/main/galaxy</galaxy>
	<planets>campaign/main/planets</planets>
	<players>campaign/main2/players</players>
	<talks>campaign/main/talks</talks>
	<tech>campaign/main/tech</tech>
	<test>campaign/main/test</test>
	<walks>campaign/main/walks</walks>
	<scripting>skirmish/human/scripting</scripting>
	<chats>campaign/main/chat</chats>
	<spies>campaign/main/spies</spies>
	<parameters 
		groundRadarUnitSize="35" 
		fleetRadarUnitSize="25" 
		researchSpeed="8" 
		productionUnit="0.004" 
		constructionSpeed="20" 
		constructionCost="20" 
		repairSpeed="10" 
		repairCost="2" 
		costToHitpoints="10" 
		nearbyDistance="10" 
		simulationRatio="10" 
		fleetSpeed="0.0064" 
		stationLimit="3" 
		battleshipLimit="3" 
		fighterLimit="30" 
		mediumshipLimit="25"
		radarShareLimit="80"
		blackMarketRestockTime="4320"
	/>
</definition>
