=== akarnokd/open-ig/trunk/open-ig/data/generic/schemas/planets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="planets">
		<xs:annotation>
			<xs:documentation>The definition of planets and buildings on them.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="planet" type="planet" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation><xs:documentation>A planet's definition.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="planet">
		<xs:annotation><xs:documentation>A planet's definition.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="surface" type="surface">
				<xs:annotation><xs:documentation>The surface definition.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="inventory" type="inventory">
				<xs:annotation><xs:documentation>The preset inventory.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="buildings" type="buildings">
				<xs:annotation><xs:documentation>The placed buildings.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The planet's unique identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The language independent name of the planet.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The optional locale specific name of the planet.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="x" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The X coordinate of the planet in the galaxy-background sized coordinate system.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="y" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The Y coordinate of the planet in the galaxy-background sized coordinate system.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="size" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The planet size in pixels when viewed with the maximal galaxy zoom.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="owner" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The player id who owns the planet, missing or empty if the planet is not populated.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="race" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The race who occupies the planet.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="rotate" use="required">
			<xs:annotation><xs:documentation>The planet rotation direction. See RotationDirection enum.</xs:documentation></xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="RL">
						<xs:annotation><xs:documentation>Rotation goes from right to left.</xs:documentation></xs:annotation>
					</xs:enumeration>
					<xs:enumeration value="LR">
						<xs:annotation><xs:documentation>Rotation goes from left to right.</xs:documentation></xs:annotation>
					</xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="population" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The population count.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="morale" type="zerohundred" use="required">
			<xs:annotation><xs:documentation>The population morale between 0 and 100.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="allocation" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The energy and worker allocation strategy. See ResourceAllocationStrategy enum.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="autobuild" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The autobuild settings. See AutoBuild enum.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="tax" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The tax settings. See TaxLevel enum.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="tax-income" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The tax income from yesterday.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="trade-income" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The trade income from yesterday.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="zerohundred">
		<xs:annotation><xs:documentation>A decimal value between 0 and 100.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="surface">
		<xs:annotation><xs:documentation>The surface definition.</xs:documentation></xs:annotation>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The surface type as specified in galaxy.xml .</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="id" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The index of the surface variant.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="inventory">
		<xs:annotation><xs:documentation>The preset inventory.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="item" type="item" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The inventory item.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="item">
		<xs:annotation><xs:documentation>The inventory item.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology identifier as in tech.xml.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="count" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The number of items.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="owner" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The owner of the inventory item.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="buildings">
		<xs:annotation><xs:documentation>The placed buildings.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="building" type="building" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The building's definition.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="building">
		<xs:annotation><xs:documentation>The building's definition.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The building identifier as in buildings.xml.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="tech" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology selection.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="x" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The building's location.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="y" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The building's location.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="enabled" type="xs:boolean" use="required">
			<xs:annotation><xs:documentation>Is the building enabled?</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="repairing" type="xs:boolean" use="required">
			<xs:annotation><xs:documentation>Is the building actively repaired?</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="energy" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The energy allocated to this building.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="worker" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The worker allocated to this building.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="level" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The upgrade level of the building.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="hp" type="xs:nonNegativeInteger" use="optional">
			<xs:annotation><xs:documentation>The building's current hitpoint. If missing, it becomes the maximum hitpoints.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="build" type="xs:nonNegativeInteger" use="optional">
			<xs:annotation><xs:documentation>The building's current build level, which goes up to the maximum hitpoints. Defaults to the building's maximum hitpoints if empty or missing.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/dlc/gump891202-racemod-0.1/generic/skirmish/racemod-0.1/planets.xml
<?xml version='1.0' encoding='UTF-8'?>
<planets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/planets.xsd">
  <planet id='Achilles' name='Achilles' x='308' y='408' size='30' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='2'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Andromeda 1' name='Andromeda 1' x='868' y='628' size='18' rotate='LR' owner='Ecalep' race='ecalep' population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='neptoplasm' id='1'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Andromeda 2' name='Andromeda 2' x='912' y='614' size='30' rotate='LR' owner='Ecalep' race='ecalep' population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='neptoplasm' id='2'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Andromeda 3' name='Andromeda 3' x='882' y='590' size='24' rotate='LR' owner='Ecalep' race='ecalep' population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='neptoplasm' id='3'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Andromeda 4' name='Andromeda 4' x='920' y='574' size='18' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='neptoplasm' id='1'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Andromeda 5' name='Andromeda 5' x='970' y='494' size='30' rotate='RL' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='neptoplasm' id='4'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Andromeda 6' name='Andromeda 6' x='846' y='542' size='24' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='earth' id='3'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Andromeda 7' name='Andromeda 7' x='974' y='588' size='18' rotate='RL' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='neptoplasm' id='3'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 1' name='Center 1' x='312' y='330' size='18' rotate='LR' owner='Ychom' race='ychom' population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='rocky' id='1'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 2' name='Center 2' x='350' y='316' size='30' rotate='RL' owner='Ychom' race='ychom' population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='cratered' id='8'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 3' name='Center 3' x='316' y='290' size='18' rotate='RL' owner='Ychom' race='ychom' population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='rocky' id='1'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 4' name='Center 4' x='278' y='302' size='24' rotate='RL' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='frozen' id='3'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 5' name='Center 5' x='352' y='276' size='18' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='cratered' id='7'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 6' name='Center 6' x='298' y='250' size='24' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='frozen' id='5'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 7' name='Center 7' x='506' y='308' size='24' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='earth' id='7'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 8' name='Center 8' x='502' y='350' size='30' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='6'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 9' name='Center 9' x='540' y='332' size='30' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='8'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 10' name='Center 10' x='458' y='438' size='24' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='cratered' id='5'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 11' name='Center 11' x='454' y='344' size='24' rotate='RL' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='7'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 12' name='Center 12' x='196' y='318' size='24' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='3'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 13' name='Center 13' x='242' y='276' size='30' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='frozen' id='5'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 14' name='Center 14' x='208' y='288' size='30' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='earth' id='4'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 15' name='Center 15' x='112' y='358' size='24' rotate='LR' population='5000' owner='Empire' race='human' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='rocky' id='5'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Center 16' name='Center 16' x='294' y='374' size='18' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='frozen' id='4'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Centronom' name='Centronom' x='252' y='382' size='30' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='3'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Earth' name='Earth' label='planets.earth' x='110' y='230' size='18' rotate='RL' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='earth' id='8'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Edgepolis' name='Edgepolis' x='108' y='306' size='30' rotate='LR' population='5000' owner='Empire' race='human' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='4'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Exterior 1' name='Exterior 1' x='156' y='504' size='18' rotate='LR' population='5000' owner='Morgath' race='morgath' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='frozen' id='9'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Exterior 2' name='Exterior 2' x='170' y='536' size='30' owner="Morgath" race="morgath" rotate='LR' population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='6'/>
    <inventory/>
	<buildings/>
  </planet>
  <planet id='Exterior 3' name='Exterior 3' x='126' y='556' size='30' rotate='RL' population='5000' owner='Morgath' race='morgath'  allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='8'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Exterior 4' name='Exterior 4' x='236' y='638' size='24' rotate='RL' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='rocky' id='7'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Exterior 5' name='Exterior 5' x='290' y='598' size='30' rotate='LR' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='rocky' id='4'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Exterior 6' name='Exterior 6' x='372' y='628' size='30' rotate='RL' population='0' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='cratered' id='2'/>
    <inventory/>
    <buildings/>
  </planet>
  <planet id='Exterior 7' name='Exterior 7' x='446' y='564' size='24' rotate='RL' owner="Sullep" race="sullep" population='5000' allocation='DEFAULT' autobuild='OFF' morale='50' tax='MODERATE' tax-income='0' trade-income='0'>
    <surface type='desert' id='7'/>
    <inventory/>
    <buildings/>
  </planet>
