=== akarnokd/open-ig/trunk/open-ig/data/generic/schemas/players.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="players">
		<xs:annotation>
			<xs:documentation>Definition of players.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="player" type="player" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation><xs:documentation>Description of a player.</xs:documentation></xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="player">
		<xs:annotation><xs:documentation>Description of a player.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="inventory" type="inventory" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The initial inventory counts.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="available" type="available" minOccurs="0" maxOccurs="1">
				<xs:annotation><xs:documentation>The set of available technologies at start.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="fleet" type="fleet" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The initial fleets.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name="traits" type="traits" minOccurs="0">
				<xs:annotation><xs:documentation>The optional traits for this player.</xs:documentation></xs:annotation>
			</xs:element>
			<xs:element name='nicknames' type='nicknames' minOccurs="0">
				<xs:annotation><xs:documentation>The optional nicknames to be used for the larger ships. Represent label references.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The player's unique identifier.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="race" type="xs:string" use="required">
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The label for the full name of the empire. The short name is derived by appending ".short".</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="icon" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The icon for the fleets.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="color" type="hex8" use="required">
			<xs:annotation><xs:documentation>The ARGB color used for labeling objects of this player (e.g., planets and fleets).</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="picture" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The race picture for the database screen.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="user" type="xs:boolean" use="optional">
			<xs:annotation><xs:documentation>Is this the active player accessible throught the UI (e.g., main player)?</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="money" type="nonNegativeLong" use="required">
			<xs:annotation><xs:documentation>The player's money.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="initial-stance" type="zerohundred" use="required">
			<xs:annotation><xs:documentation>The initial stance towards other players when discovered.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="ai" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The AI mode. See the AIMode enum.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="colonization-limit" type="xs:int" use="required">
			<xs:annotation><xs:documentation>Number of planets to colonize by the AI. -1 represents unlimited.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="diplomacy-head" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The head animation used by the diplomacy screen.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="ratios" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The ratio of offensive, defensive and social activitios for the AI, expressed as free values (comma separated).</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="exploration-inner-limit" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>Comma separated values of a rectangles top-left X, Y, width and height in the galaxy map's coordinate space.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="exploration-outer-limit" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>Comma separated values of a rectangles top-left X, Y, width and height in the galaxy map's coordinate space.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="war-threshold" type="xs:nonNegativeInteger" use="optional">
			<xs:annotation><xs:documentation>The AI's diplomatic relation threshold to consider a player for war.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="police-ratio" type="xs:nonNegativeInteger" use="optional">
			<xs:annotation><xs:documentation>The morale boost in 100s caused by the police's presence.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="nodiplomacy" type="xs:boolean" use="optional">
			<xs:annotation><xs:documentation>Does this player do diplomacy?</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="nodatabase" type="xs:boolean" use="optional">
			<xs:annotation><xs:documentation>The player should not occur in the database screen.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="hex8">
		<xs:annotation><xs:documentation>8 character hexadecimal value.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="8"/>
			<xs:pattern value="[a-fA-F0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zerohundred">
		<xs:annotation><xs:documentation>A real value between 0 and 100.</xs:documentation></xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nonNegativeLong">
		<xs:annotation><xs:documentation>A non-negative long value (64 bit)</xs:documentation></xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="0"/>
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="9223372036854775807"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="inventory">
		<xs:annotation><xs:documentation>The inventory count.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology identifier in tech.xml.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="count" type="xs:nonNegativeInteger" use="required">
			<xs:annotation><xs:documentation>The number of items in the inventory.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="available">
		<xs:annotation><xs:documentation>The available technologies.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="type" type="available-type" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The definition of the available technology.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="available-type">
		<xs:annotation><xs:documentation>The definition of the available technology.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology identifier in tech.xml.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="list" use="required">
			<xs:annotation><xs:documentation>The list of best technologies to fill in the slots.</xs:documentation></xs:annotation>
			<xs:simpleType>
				<xs:list itemType="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="fleet">
		<xs:sequence>
			<xs:element name="item" type="fleet-item" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The fleet item.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="optional">
			<xs:annotation><xs:documentation>The optional unique identifier of the fleet. If omitted, the fleet gets one.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="x" type="xs:decimal" use="required">
			<xs:annotation><xs:documentation>The fleet's current X coordinate on the galaxy coordinates.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="y" type="xs:decimal" use="required">
			<xs:annotation><xs:documentation>The fleet's current Y coordinate on the galaxy coordinates.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The name of the fleet. If the name starts with @, the whole text is used for the fleet name (including @).</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="fleet-item">
		<xs:annotation><xs:documentation>The individual fleet item.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="slot" type="slot" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>The filled-in slot definitions.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required">
			<xs:annotation><xs:documentation>The unique identifier of the item.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology id of the fleet item in tech.xml</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="count" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The number of items of the current type.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="tag" type="xs:string" use="optional">
			<xs:annotation><xs:documentation>The optional tagging of the item.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="slot">
		<xs:annotation><xs:documentation>The filled-in slot definitions.</xs:documentation></xs:annotation>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The non-fixed slot identifier as found in tech.xml.</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation><xs:documentation>The technology id equipping this slot from tech.xml</xs:documentation></xs:annotation>
		</xs:attribute>
		<xs:attribute name="count" type="xs:positiveInteger" use="required">
			<xs:annotation><xs:documentation>The number of items in the slot.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="traits">
		<xs:annotation><xs:documentation>The list of trait ids affecting this player.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name="trait" type='trait' minOccurs='0' maxOccurs='unbounded'>
				<xs:annotation><xs:documentation>The reference to a global trait.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="trait">
		<xs:annotation><xs:documentation>A reference to a global trait.</xs:documentation></xs:annotation>
		<xs:attribute name='id' type="xs:string" use="required">
			<xs:annotation><xs:documentation>The ID of the global trait.</xs:documentation></xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name='nicknames'>
		<xs:annotation><xs:documentation>The optional nicknames to be used for the larger ships. Represent label references.</xs:documentation></xs:annotation>
		<xs:sequence>
			<xs:element name='nickname' type='xs:string' minOccurs="0" maxOccurs="unbounded">
				<xs:annotation><xs:documentation>A concrete nickname label reference.</xs:documentation></xs:annotation>
			</xs:element>
		</xs:sequence>		
	</xs:complexType>
</xs:schema>

=== akarnokd/open-ig/trunk/open-ig/data/generic/campaign/main/players.xml
<?xml version='1.0' encoding='UTF-8'?>
<players xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/players.xsd">
	<player id='Empire' race='human' name='players.empire'
		icon='starmap/fleets/human_fleet'
		color='FFFCB000'
		picture='database/freenations'
		user='true'
		money='32000'
		initial-stance='50'
		ai='NONE'
		colonization-limit='-1'
		diplomacy-head='diplomacy/dipfej7'
	>
	<!-- Initial inventory.
	 -->
	 <!-- Actually, this should be the reward for Mission 3. 
		<inventory id='Shield1' count='1'/>
	 -->
	<!-- Available technology override.
		<available>
			<type id='' list=''/>
		</available>
	-->
	<!-- Initial fleets. -->
		<fleet id='0' x='330' y='440' name='@MainFleet'>
			<item id='-1' type='Destroyer1' count='1' tag='CampaignMainShip1'>
				<slot id='laser' type='Laser1' count='3'/>
				<slot id='hyperdrive' type='HyperDrive1' count='1'/>
			</item>
			<item id='-1' type='Fighter1' count='3' />
		</fleet>
		<nicknames>
			<nickname>Berserker</nickname>
			<nickname>Executor</nickname>
			<nickname>Chaotic</nickname>
			<nickname>Excalibur</nickname>
			<nickname>Ivan</nickname>
			<nickname>Crusher</nickname>
			<nickname>Metdown</nickname>
			<nickname>Hunter</nickname>
			<nickname>Falcon</nickname>
			<nickname>Eagle</nickname>
			<nickname>Terminator</nickname>
			<nickname>Tiger</nickname>
			<nickname>Puma</nickname>
			<nickname>Giant</nickname>
			<nickname>The Hammer</nickname>
			<nickname>Dracula</nickname>
			<nickname>Nightmare</nickname>
			<nickname>The Anvil</nickname>
			<nickname>Red Star</nickname>
			<nickname>Lightning</nickname>
			<nickname>Lion</nickname>
			<nickname>Wildcat</nickname>
			<nickname>Bat</nickname>
			<nickname>Shark</nickname>
			<nickname>Condor</nickname>
			<nickname>Neptune</nickname>
			<nickname>Ares</nickname>
			<nickname>Minerva</nickname>
			<nickname>Odin</nickname>
			<nickname>Black Knight</nickname>
			<nickname>Sword</nickname>
			<nickname>Chronos</nickname>
			<nickname>Dingo</nickname>
			<nickname>Lynx</nickname>
			<nickname>Azor</nickname>
			<nickname>Peregrin</nickname>
			<nickname>Grizzlie</nickname>
			<nickname>Orca</nickname>
			<nickname>Phoenix</nickname>
			<nickname>Dolphin</nickname>
			<nickname>Guepard</nickname>
			<nickname>Ocean</nickname>
			<nickname>Raider</nickname>
			<nickname>Green Dragon</nickname>
		</nicknames>
	</player>
	<player id='Garthog' race='garthog' name='players.garthog'
		icon='starmap/fleets/garthog_fleet'
		color='FFFC2828'
		picture='database/garthog'
		money='32000'
		initial-stance='40'
		ai='DEFAULT' ratios='1,2,1'
		exploration-inner-limit=''
		exploration-outer-limit=''
		colonization-limit='0'
		war-threshold='98'
		diplomacy-head='diplomacy/dipfej9'
		police-ratio='15'
	>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='MediumTank' list=''/>
			<type id='RocketLauncher1' list=''/>
			<type id='OrbitalFactory' list=''/>
			<type id='SpySatellite1' list=''/>
			<type id='HyperDrive3' list=''/>
			<type id='Laser2' list=''/>
			<type id='IonCannon' list=''/>
			<type id='TradeCenter' list=''/>
			<type id='Fortress' list=''/>
			<type id='GarthogRadarJammer' list=''/>
		</available>
	</player>
	<player id='Morgath' race='morgath' name='players.morgath'
		icon='starmap/fleets/morgath_fleet'
		color='FFFCFCFC'
		picture='database/morgath'
		money='32000'
		initial-stance='40'
		colonization-limit='3'
		diplomacy-head='diplomacy/dipfej1'
		police-ratio='15'
		ai='DEFAULT' ratios='1,2,1'
	>
		<inventory id='ColonyShip' count='2'/>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='ColonyShip' list=''/>
			<type id="MediumTank" list=""/>
			<type id="RocketLauncher1" list=""/>
			<type id='OrbitalFactory' list=''/>
			<type id='TradeCenter' list=''/>
			<type id='Fortress' list=''/>
		</available>
	</player>
	<player id='Ychom' race='ychom' name='players.ychom'
		icon='starmap/fleets/ychom_fleet'
		color='FF00FFFF'
		picture='database/ychom'
		money='32000'
		initial-stance='40'
		colonization-limit='3'
		diplomacy-head='diplomacy/dipfej2'
		police-ratio='15'
		ai='DEFAULT' ratios='1,2,1'
	>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='MediumTank' list=''/>
			<type id='YchomMinelayer' list=''/>
			<type id='RocketLauncher1' list=''/>
			<type id='ColonyShip' list=''/>
			<type id='OrbitalFactory' list=''/>
			<type id='TradeCenter' list=''/>
			<type id='Fortress' list=''/>
		</available>
	</player>
	<player id='Dribs' race='dribs' name='players.dribs'
		icon='starmap/fleets/dribs_fleet'
		color='FFFC00FC'
		picture='database/drib'
		money='32000'
		initial-stance='40'
		colonization-limit='2'
		diplomacy-head='diplomacy/dipfej3'
		police-ratio='15'
		ai='DEFAULT' ratios='1,2,1'
	>
		<inventory id='ColonyShip' count='1'/>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='ColonyShip' list=''/>
			<type id='MediumTank' list=''/>
			<type id='DribsParalizer' list=''/>
			<type id='RocketLauncher1' list=''/>
			<type id='OrbitalFactory' list=''/>
			<type id='TradeCenter' list=''/>
			<type id='Fortress' list=''/>
		</available>
	</player>
	<player id='Sullep' race='sullep' name='players.sullep'
		icon='starmap/fleets/sullep_fleet'
		color='FFFCFC58'
		picture='database/sullep'
		money='32000'
		initial-stance='40'
		colonization-limit='0'
		diplomacy-head='diplomacy/dipfej4'
		police-ratio='15'
		ai='DEFAULT' ratios='1,2,1'
	>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='ColonyShip' list=''/>
			<type id='MediumTank' list=''/>
			<type id='RocketLauncher1' list=''/>
			<type id='OrbitalFactory' list=''/>
			<type id='TradeCenter' list=''/>
			<type id='Fortress' list=''/>
			<type id='SullepArtillery' list=''/>
		</available>
	</player>
	<player id='Dargslan' race='dargslan' name='players.dargslan'
		icon='starmap/fleets/dargslan_fleet'
		color='FF009800'
		picture='database/dargslan'
		money='32000'
		initial-stance='10'
		exploration-inner-limit=''
		exploration-outer-limit=''
		colonization-limit='0'
		diplomacy-head='diplomacy/dipfej5'
		war-threshold='90'
		police-ratio='15'
		ai='DEFAULT' ratios='1,2,1'
	>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='ColonyShip' list=''/>
			<type id='Bomb2' list=''/>
			<type id='Rocket2' list=''/>
			<type id='MultiheadedRocket' list=''/>
			<type id='MediumTank' list=''/>
			<type id='HeavyTank' list=''/>
			<type id='DargslanSelfRepairTank' list=''/>
			<type id='RocketLauncher2' list=''/>
			<type id='OrbitalFactory' list=''/>
			<type id='TradeCenter' list=''/>
			<type id='Fortress' list=''/>
		</available>
	</player>
	<player id='Ecalep' race='ecalep' name='players.ecalep'
		icon='starmap/fleets/ecalep_fleet'
		color='FFB0FC6C'
		picture='database/ecalep'
		money='32000'
		initial-stance='40'
		colonization-limit='1'
		diplomacy-head='diplomacy/dipfej6'
		police-ratio='15'
		ai='DEFAULT' ratios='1,2,1'
	>
		<inventory id='ColonyShip' count='1'/>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='MultiheadedRocket' list=''/>
			<type id='ColonyShip' list=''/>
			<type id="HeavyTank" list=""/>
			<type id="EcalepRocketJammer" list=""/>
			<type id="RocketLauncher1" list=""/>
			<type id='OrbitalFactory' list=''/>
			<type id='TradeCenter' list=''/>
			<type id='Fortress' list=''/>
		</available>
	</player>
	<player id='FreeTraders' race='human' name='players.free_traders'
		icon='starmap/fleets/free_traders_fleet'
		color='FF3C3CFC'
		picture='database/freetraders'
		money='32000'
		initial-stance='50'
		colonization-limit='2'
		diplomacy-head='diplomacy/dipfej7'
		ai='DEFAULT' ratios='1,2,1'
	>
		<inventory id='ColonyShip' count='2'/>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='ColonyShip' list=''/>
			<type id='MediumTank' list=''/>
			<type id='RocketLauncher1' list=''/>
			<type id='ECM1' list=''/>
			<type id='Cruiser1' list=''/>
			<type id='Fighter2' list=''/>
			<type id='Fighter3' list=''/>
			<type id='Fighter4' list=''/>
			<type id='Shield2' list=''/>
			<type id='Shield3' list=''/>
			<type id='HyperDrive1' list=''/>
			<type id='HyperDrive2' list=''/>
			<type id='HyperDrive3' list=''/>
			<type id='Laser2' list=''/>
			<type id='Laser3' list=''/>
			<type id='OrbitalFactory' list=''/>
			<type id='Fortress' list=''/>
		</available>
	</player>
	<player id='FreeNations' race='human' name='players.free_nations'
		icon='starmap/fleets/free_nations_fleet'
		color='FF94A4FC'
		picture='database/freenations'
		money='32000'
		initial-stance='50'
		colonization-limit='0'
		diplomacy-head='diplomacy/dipfej8'
		ai='DEFAULT' ratios='1,2,1'
	>
		<available>
			<type id='PhoodFactory' list=''/>
			<type id='ColonyShip' list=''/>
			<type id='MediumTank' list=''/>
			<type id='RocketLauncher1' list=''/>
			<type id='ECM1' list=''/>
			<type id='Cruiser1' list=''/>
			<type id='Fighter2' list=''/>
			<type id='Fighter3' list=''/>
			<type id='Fighter4' list=''/>
			<type id='Shield2' list=''/>
			<type id='Shield3' list=''/>
			<type id='HyperDrive1' list=''/>
			<type id='HyperDrive2' list=''/>
			<type id='HyperDrive3' list=''/>
			<type id='Laser2' list=''/>
			<type id='Laser3' list=''/>
			<type id='OrbitalFactory' list=''/>
		</available>
	</player>
	<player id='Pirates' race='pirates' name='players.pirates'
		icon='starmap/fleets/pirates_fleet'
		color='FF95416E'
		picture='database/pirates'
		money='32000'
		initial-stance='10'
		ai='PIRATES'
		nodiplomacy='true'
		colonization-limit='0'
		police-ratio='15'
		noskirmish='true'
	>
		<available>
			<type id='ColonyShip' list=''/>
			<type id='OrbitalFactory' list=''/>
